// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePaymentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClientId         int64                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FromAccount      string                 `protobuf:"bytes,2,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	RecipientName    string                 `protobuf:"bytes,3,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"`
	RecipientAccount string                 `protobuf:"bytes,4,opt,name=recipient_account,json=recipientAccount,proto3" json:"recipient_account,omitempty"`
	Amount           float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentCode      string                 `protobuf:"bytes,6,opt,name=payment_code,json=paymentCode,proto3" json:"payment_code,omitempty"`
	ReferenceNumber  string                 `protobuf:"bytes,7,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	Purpose          string                 `protobuf:"bytes,8,opt,name=purpose,proto3" json:"purpose,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *CreatePaymentRequest) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *CreatePaymentRequest) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *CreatePaymentRequest) GetRecipientAccount() string {
	if x != nil {
		return x.RecipientAccount
	}
	return ""
}

func (x *CreatePaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentRequest) GetPaymentCode() string {
	if x != nil {
		return x.PaymentCode
	}
	return ""
}

func (x *CreatePaymentRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *CreatePaymentRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

type CreatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNumber   string                 `protobuf:"bytes,2,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	FromAccount   string                 `protobuf:"bytes,3,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccount     string                 `protobuf:"bytes,4,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	InitialAmount float64                `protobuf:"fixed64,5,opt,name=initial_amount,json=initialAmount,proto3" json:"initial_amount,omitempty"`
	FinalAmount   float64                `protobuf:"fixed64,6,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	Fee           float64                `protobuf:"fixed64,7,opt,name=fee,proto3" json:"fee,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     string                 `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreatePaymentResponse) GetOrderNumber() string {
	if x != nil {
		return x.OrderNumber
	}
	return ""
}

func (x *CreatePaymentResponse) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *CreatePaymentResponse) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *CreatePaymentResponse) GetInitialAmount() float64 {
	if x != nil {
		return x.InitialAmount
	}
	return 0
}

func (x *CreatePaymentResponse) GetFinalAmount() float64 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

func (x *CreatePaymentResponse) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *CreatePaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreatePaymentResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type PaymentRecipient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId      int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AccountNumber string                 `protobuf:"bytes,4,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Order         int32                  `protobuf:"varint,5,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRecipient) Reset() {
	*x = PaymentRecipient{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRecipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRecipient) ProtoMessage() {}

func (x *PaymentRecipient) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRecipient.ProtoReflect.Descriptor instead.
func (*PaymentRecipient) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentRecipient) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaymentRecipient) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *PaymentRecipient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PaymentRecipient) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *PaymentRecipient) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type ReorderPaymentRecipientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      int64                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	OrderedIds    []int64                `protobuf:"varint,2,rep,packed,name=ordered_ids,json=orderedIds,proto3" json:"ordered_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderPaymentRecipientsRequest) Reset() {
	*x = ReorderPaymentRecipientsRequest{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderPaymentRecipientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderPaymentRecipientsRequest) ProtoMessage() {}

func (x *ReorderPaymentRecipientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderPaymentRecipientsRequest.ProtoReflect.Descriptor instead.
func (*ReorderPaymentRecipientsRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *ReorderPaymentRecipientsRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *ReorderPaymentRecipientsRequest) GetOrderedIds() []int64 {
	if x != nil {
		return x.OrderedIds
	}
	return nil
}

type ReorderPaymentRecipientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderPaymentRecipientsResponse) Reset() {
	*x = ReorderPaymentRecipientsResponse{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderPaymentRecipientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderPaymentRecipientsResponse) ProtoMessage() {}

func (x *ReorderPaymentRecipientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderPaymentRecipientsResponse.ProtoReflect.Descriptor instead.
func (*ReorderPaymentRecipientsResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

type CreatePaymentRecipientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      int64                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AccountNumber string                 `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRecipientRequest) Reset() {
	*x = CreatePaymentRecipientRequest{}
	mi := &file_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRecipientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRecipientRequest) ProtoMessage() {}

func (x *CreatePaymentRecipientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRecipientRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRecipientRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePaymentRecipientRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *CreatePaymentRecipientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePaymentRecipientRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type CreatePaymentRecipientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipient     *PaymentRecipient      `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRecipientResponse) Reset() {
	*x = CreatePaymentRecipientResponse{}
	mi := &file_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRecipientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRecipientResponse) ProtoMessage() {}

func (x *CreatePaymentRecipientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRecipientResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentRecipientResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePaymentRecipientResponse) GetRecipient() *PaymentRecipient {
	if x != nil {
		return x.Recipient
	}
	return nil
}

type GetPaymentRecipientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      int64                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRecipientsRequest) Reset() {
	*x = GetPaymentRecipientsRequest{}
	mi := &file_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRecipientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRecipientsRequest) ProtoMessage() {}

func (x *GetPaymentRecipientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRecipientsRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRecipientsRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{7}
}

func (x *GetPaymentRecipientsRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type GetPaymentRecipientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipients    []*PaymentRecipient    `protobuf:"bytes,1,rep,name=recipients,proto3" json:"recipients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRecipientsResponse) Reset() {
	*x = GetPaymentRecipientsResponse{}
	mi := &file_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRecipientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRecipientsResponse) ProtoMessage() {}

func (x *GetPaymentRecipientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRecipientsResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentRecipientsResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{8}
}

func (x *GetPaymentRecipientsResponse) GetRecipients() []*PaymentRecipient {
	if x != nil {
		return x.Recipients
	}
	return nil
}

type DeletePaymentRecipientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId      int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePaymentRecipientRequest) Reset() {
	*x = DeletePaymentRecipientRequest{}
	mi := &file_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePaymentRecipientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePaymentRecipientRequest) ProtoMessage() {}

func (x *DeletePaymentRecipientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePaymentRecipientRequest.ProtoReflect.Descriptor instead.
func (*DeletePaymentRecipientRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePaymentRecipientRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeletePaymentRecipientRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type DeletePaymentRecipientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePaymentRecipientResponse) Reset() {
	*x = DeletePaymentRecipientResponse{}
	mi := &file_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePaymentRecipientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePaymentRecipientResponse) ProtoMessage() {}

func (x *DeletePaymentRecipientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePaymentRecipientResponse.ProtoReflect.Descriptor instead.
func (*DeletePaymentRecipientResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{10}
}

type UpdatePaymentRecipientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId      int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AccountNumber string                 `protobuf:"bytes,4,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentRecipientRequest) Reset() {
	*x = UpdatePaymentRecipientRequest{}
	mi := &file_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentRecipientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentRecipientRequest) ProtoMessage() {}

func (x *UpdatePaymentRecipientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentRecipientRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentRecipientRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{11}
}

func (x *UpdatePaymentRecipientRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePaymentRecipientRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *UpdatePaymentRecipientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePaymentRecipientRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type UpdatePaymentRecipientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipient     *PaymentRecipient      `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentRecipientResponse) Reset() {
	*x = UpdatePaymentRecipientResponse{}
	mi := &file_payment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentRecipientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentRecipientResponse) ProtoMessage() {}

func (x *UpdatePaymentRecipientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentRecipientResponse.ProtoReflect.Descriptor instead.
func (*UpdatePaymentRecipientResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{12}
}

func (x *UpdatePaymentRecipientResponse) GetRecipient() *PaymentRecipient {
	if x != nil {
		return x.Recipient
	}
	return nil
}

type Payment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNumber     string                 `protobuf:"bytes,2,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	FromAccount     string                 `protobuf:"bytes,3,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccount       string                 `protobuf:"bytes,4,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	InitialAmount   float64                `protobuf:"fixed64,5,opt,name=initial_amount,json=initialAmount,proto3" json:"initial_amount,omitempty"`
	FinalAmount     float64                `protobuf:"fixed64,6,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	Fee             float64                `protobuf:"fixed64,7,opt,name=fee,proto3" json:"fee,omitempty"`
	PaymentCode     string                 `protobuf:"bytes,8,opt,name=payment_code,json=paymentCode,proto3" json:"payment_code,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,9,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	Purpose         string                 `protobuf:"bytes,10,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Timestamp       string                 `protobuf:"bytes,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status          string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	RecipientName   string                 `protobuf:"bytes,13,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"`
	SenderName      string                 `protobuf:"bytes,14,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	SenderAddress   string                 `protobuf:"bytes,15,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`
	Currency        string                 `protobuf:"bytes,16,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_payment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{13}
}

func (x *Payment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Payment) GetOrderNumber() string {
	if x != nil {
		return x.OrderNumber
	}
	return ""
}

func (x *Payment) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *Payment) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *Payment) GetInitialAmount() float64 {
	if x != nil {
		return x.InitialAmount
	}
	return 0
}

func (x *Payment) GetFinalAmount() float64 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

func (x *Payment) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Payment) GetPaymentCode() string {
	if x != nil {
		return x.PaymentCode
	}
	return ""
}

func (x *Payment) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *Payment) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *Payment) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Payment) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *Payment) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *Payment) GetSenderAddress() string {
	if x != nil {
		return x.SenderAddress
	}
	return ""
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetPaymentByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     int64                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	ClientId      int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentByIdRequest) Reset() {
	*x = GetPaymentByIdRequest{}
	mi := &file_payment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentByIdRequest) ProtoMessage() {}

func (x *GetPaymentByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentByIdRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentByIdRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{14}
}

func (x *GetPaymentByIdRequest) GetPaymentId() int64 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *GetPaymentByIdRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type GetPaymentByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentByIdResponse) Reset() {
	*x = GetPaymentByIdResponse{}
	mi := &file_payment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentByIdResponse) ProtoMessage() {}

func (x *GetPaymentByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentByIdResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentByIdResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{15}
}

func (x *GetPaymentByIdResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type GetPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      int64                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	DateFrom      string                 `protobuf:"bytes,2,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,3,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	AmountMin     float64                `protobuf:"fixed64,4,opt,name=amount_min,json=amountMin,proto3" json:"amount_min,omitempty"`
	AmountMax     float64                `protobuf:"fixed64,5,opt,name=amount_max,json=amountMax,proto3" json:"amount_max,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentsRequest) Reset() {
	*x = GetPaymentsRequest{}
	mi := &file_payment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentsRequest) ProtoMessage() {}

func (x *GetPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentsRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{16}
}

func (x *GetPaymentsRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *GetPaymentsRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *GetPaymentsRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

func (x *GetPaymentsRequest) GetAmountMin() float64 {
	if x != nil {
		return x.AmountMin
	}
	return 0
}

func (x *GetPaymentsRequest) GetAmountMax() float64 {
	if x != nil {
		return x.AmountMax
	}
	return 0
}

func (x *GetPaymentsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetPaymentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPaymentsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentsResponse) Reset() {
	*x = GetPaymentsResponse{}
	mi := &file_payment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentsResponse) ProtoMessage() {}

func (x *GetPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentsResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{17}
}

func (x *GetPaymentsResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

type CreateTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      int64                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FromAccount   string                 `protobuf:"bytes,2,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccount     string                 `protobuf:"bytes,3,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransferRequest) Reset() {
	*x = CreateTransferRequest{}
	mi := &file_payment_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferRequest) ProtoMessage() {}

func (x *CreateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferRequest.ProtoReflect.Descriptor instead.
func (*CreateTransferRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{18}
}

func (x *CreateTransferRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *CreateTransferRequest) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *CreateTransferRequest) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *CreateTransferRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNumber   string                 `protobuf:"bytes,2,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	FromAccount   string                 `protobuf:"bytes,3,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccount     string                 `protobuf:"bytes,4,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	InitialAmount float64                `protobuf:"fixed64,5,opt,name=initial_amount,json=initialAmount,proto3" json:"initial_amount,omitempty"`
	FinalAmount   float64                `protobuf:"fixed64,6,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	ExchangeRate  float64                `protobuf:"fixed64,7,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
	Fee           float64                `protobuf:"fixed64,8,opt,name=fee,proto3" json:"fee,omitempty"`
	Timestamp     string                 `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransferResponse) Reset() {
	*x = CreateTransferResponse{}
	mi := &file_payment_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferResponse) ProtoMessage() {}

func (x *CreateTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferResponse.ProtoReflect.Descriptor instead.
func (*CreateTransferResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{19}
}

func (x *CreateTransferResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateTransferResponse) GetOrderNumber() string {
	if x != nil {
		return x.OrderNumber
	}
	return ""
}

func (x *CreateTransferResponse) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *CreateTransferResponse) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *CreateTransferResponse) GetInitialAmount() float64 {
	if x != nil {
		return x.InitialAmount
	}
	return 0
}

func (x *CreateTransferResponse) GetFinalAmount() float64 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

func (x *CreateTransferResponse) GetExchangeRate() float64 {
	if x != nil {
		return x.ExchangeRate
	}
	return 0
}

func (x *CreateTransferResponse) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *CreateTransferResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type Transfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNumber   string                 `protobuf:"bytes,2,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	FromAccount   string                 `protobuf:"bytes,3,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccount     string                 `protobuf:"bytes,4,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	InitialAmount float64                `protobuf:"fixed64,5,opt,name=initial_amount,json=initialAmount,proto3" json:"initial_amount,omitempty"`
	FinalAmount   float64                `protobuf:"fixed64,6,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	ExchangeRate  float64                `protobuf:"fixed64,7,opt,name=exchange_rate,json=exchangeRate,proto3" json:"exchange_rate,omitempty"`
	Fee           float64                `protobuf:"fixed64,8,opt,name=fee,proto3" json:"fee,omitempty"`
	Timestamp     string                 `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_payment_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{20}
}

func (x *Transfer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transfer) GetOrderNumber() string {
	if x != nil {
		return x.OrderNumber
	}
	return ""
}

func (x *Transfer) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *Transfer) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *Transfer) GetInitialAmount() float64 {
	if x != nil {
		return x.InitialAmount
	}
	return 0
}

func (x *Transfer) GetFinalAmount() float64 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

func (x *Transfer) GetExchangeRate() float64 {
	if x != nil {
		return x.ExchangeRate
	}
	return 0
}

func (x *Transfer) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Transfer) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type GetTransfersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      int64                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransfersRequest) Reset() {
	*x = GetTransfersRequest{}
	mi := &file_payment_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransfersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransfersRequest) ProtoMessage() {}

func (x *GetTransfersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransfersRequest.ProtoReflect.Descriptor instead.
func (*GetTransfersRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{21}
}

func (x *GetTransfersRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type GetTransfersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfers     []*Transfer            `protobuf:"bytes,1,rep,name=transfers,proto3" json:"transfers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransfersResponse) Reset() {
	*x = GetTransfersResponse{}
	mi := &file_payment_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransfersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransfersResponse) ProtoMessage() {}

func (x *GetTransfersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransfersResponse.ProtoReflect.Descriptor instead.
func (*GetTransfersResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{22}
}

func (x *GetTransfersResponse) GetTransfers() []*Transfer {
	if x != nil {
		return x.Transfers
	}
	return nil
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\apayment\"\xaa\x02\n" +
	"\x14CreatePaymentRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x03R\bclientId\x12!\n" +
	"\ffrom_account\x18\x02 \x01(\tR\vfromAccount\x12%\n" +
	"\x0erecipient_name\x18\x03 \x01(\tR\rrecipientName\x12+\n" +
	"\x11recipient_account\x18\x04 \x01(\tR\x10recipientAccount\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12!\n" +
	"\fpayment_code\x18\x06 \x01(\tR\vpaymentCode\x12)\n" +
	"\x10reference_number\x18\a \x01(\tR\x0freferenceNumber\x12\x18\n" +
	"\apurpose\x18\b \x01(\tR\apurpose\"\x9e\x02\n" +
	"\x15CreatePaymentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\forder_number\x18\x02 \x01(\tR\vorderNumber\x12!\n" +
	"\ffrom_account\x18\x03 \x01(\tR\vfromAccount\x12\x1d\n" +
	"\n" +
	"to_account\x18\x04 \x01(\tR\ttoAccount\x12%\n" +
	"\x0einitial_amount\x18\x05 \x01(\x01R\rinitialAmount\x12!\n" +
	"\ffinal_amount\x18\x06 \x01(\x01R\vfinalAmount\x12\x10\n" +
	"\x03fee\x18\a \x01(\x01R\x03fee\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\tR\ttimestamp\"\x90\x01\n" +
	"\x10PaymentRecipient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\x0eaccount_number\x18\x04 \x01(\tR\raccountNumber\x12\x14\n" +
	"\x05order\x18\x05 \x01(\x05R\x05order\"_\n" +
	"\x1fReorderPaymentRecipientsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x03R\bclientId\x12\x1f\n" +
	"\vordered_ids\x18\x02 \x03(\x03R\n" +
	"orderedIds\"\"\n" +
	" ReorderPaymentRecipientsResponse\"w\n" +
	"\x1dCreatePaymentRecipientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x03R\bclientId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\tR\raccountNumber\"Y\n" +
	"\x1eCreatePaymentRecipientResponse\x127\n" +
	"\trecipient\x18\x01 \x01(\v2\x19.payment.PaymentRecipientR\trecipient\":\n" +
	"\x1bGetPaymentRecipientsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x03R\bclientId\"Y\n" +
	"\x1cGetPaymentRecipientsResponse\x129\n" +
	"\n" +
	"recipients\x18\x01 \x03(\v2\x19.payment.PaymentRecipientR\n" +
	"recipients\"L\n" +
	"\x1dDeletePaymentRecipientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\" \n" +
	"\x1eDeletePaymentRecipientResponse\"\x87\x01\n" +
	"\x1dUpdatePaymentRecipientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\x0eaccount_number\x18\x04 \x01(\tR\raccountNumber\"Y\n" +
	"\x1eUpdatePaymentRecipientResponse\x127\n" +
	"\trecipient\x18\x01 \x01(\v2\x19.payment.PaymentRecipientR\trecipient\"\x83\x04\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\forder_number\x18\x02 \x01(\tR\vorderNumber\x12!\n" +
	"\ffrom_account\x18\x03 \x01(\tR\vfromAccount\x12\x1d\n" +
	"\n" +
	"to_account\x18\x04 \x01(\tR\ttoAccount\x12%\n" +
	"\x0einitial_amount\x18\x05 \x01(\x01R\rinitialAmount\x12!\n" +
	"\ffinal_amount\x18\x06 \x01(\x01R\vfinalAmount\x12\x10\n" +
	"\x03fee\x18\a \x01(\x01R\x03fee\x12!\n" +
	"\fpayment_code\x18\b \x01(\tR\vpaymentCode\x12)\n" +
	"\x10reference_number\x18\t \x01(\tR\x0freferenceNumber\x12\x18\n" +
	"\apurpose\x18\n" +
	" \x01(\tR\apurpose\x12\x1c\n" +
	"\ttimestamp\x18\v \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12%\n" +
	"\x0erecipient_name\x18\r \x01(\tR\rrecipientName\x12\x1f\n" +
	"\vsender_name\x18\x0e \x01(\tR\n" +
	"senderName\x12%\n" +
	"\x0esender_address\x18\x0f \x01(\tR\rsenderAddress\x12\x1a\n" +
	"\bcurrency\x18\x10 \x01(\tR\bcurrency\"S\n" +
	"\x15GetPaymentByIdRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x03R\tpaymentId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\"D\n" +
	"\x16GetPaymentByIdResponse\x12*\n" +
	"\apayment\x18\x01 \x01(\v2\x10.payment.PaymentR\apayment\"\xeb\x01\n" +
	"\x12GetPaymentsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x03R\bclientId\x12\x1b\n" +
	"\tdate_from\x18\x02 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\x03 \x01(\tR\x06dateTo\x12\x1d\n" +
	"\n" +
	"amount_min\x18\x04 \x01(\x01R\tamountMin\x12\x1d\n" +
	"\n" +
	"amount_max\x18\x05 \x01(\x01R\tamountMax\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\b \x01(\x05R\x06offset\"C\n" +
	"\x13GetPaymentsResponse\x12,\n" +
	"\bpayments\x18\x01 \x03(\v2\x10.payment.PaymentR\bpayments\"\x8e\x01\n" +
	"\x15CreateTransferRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x03R\bclientId\x12!\n" +
	"\ffrom_account\x18\x02 \x01(\tR\vfromAccount\x12\x1d\n" +
	"\n" +
	"to_account\x18\x03 \x01(\tR\ttoAccount\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\"\xac\x02\n" +
	"\x16CreateTransferResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\forder_number\x18\x02 \x01(\tR\vorderNumber\x12!\n" +
	"\ffrom_account\x18\x03 \x01(\tR\vfromAccount\x12\x1d\n" +
	"\n" +
	"to_account\x18\x04 \x01(\tR\ttoAccount\x12%\n" +
	"\x0einitial_amount\x18\x05 \x01(\x01R\rinitialAmount\x12!\n" +
	"\ffinal_amount\x18\x06 \x01(\x01R\vfinalAmount\x12#\n" +
	"\rexchange_rate\x18\a \x01(\x01R\fexchangeRate\x12\x10\n" +
	"\x03fee\x18\b \x01(\x01R\x03fee\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\tR\ttimestamp\"\x9e\x02\n" +
	"\bTransfer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\forder_number\x18\x02 \x01(\tR\vorderNumber\x12!\n" +
	"\ffrom_account\x18\x03 \x01(\tR\vfromAccount\x12\x1d\n" +
	"\n" +
	"to_account\x18\x04 \x01(\tR\ttoAccount\x12%\n" +
	"\x0einitial_amount\x18\x05 \x01(\x01R\rinitialAmount\x12!\n" +
	"\ffinal_amount\x18\x06 \x01(\x01R\vfinalAmount\x12#\n" +
	"\rexchange_rate\x18\a \x01(\x01R\fexchangeRate\x12\x10\n" +
	"\x03fee\x18\b \x01(\x01R\x03fee\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\tR\ttimestamp\"2\n" +
	"\x13GetTransfersRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x03R\bclientId\"G\n" +
	"\x14GetTransfersResponse\x12/\n" +
	"\ttransfers\x18\x01 \x03(\v2\x11.payment.TransferR\ttransfers2\xb4\a\n" +
	"\x0ePaymentService\x12N\n" +
	"\rCreatePayment\x12\x1d.payment.CreatePaymentRequest\x1a\x1e.payment.CreatePaymentResponse\x12H\n" +
	"\vGetPayments\x12\x1b.payment.GetPaymentsRequest\x1a\x1c.payment.GetPaymentsResponse\x12Q\n" +
	"\x0eGetPaymentById\x12\x1e.payment.GetPaymentByIdRequest\x1a\x1f.payment.GetPaymentByIdResponse\x12Q\n" +
	"\x0eCreateTransfer\x12\x1e.payment.CreateTransferRequest\x1a\x1f.payment.CreateTransferResponse\x12i\n" +
	"\x16CreatePaymentRecipient\x12&.payment.CreatePaymentRecipientRequest\x1a'.payment.CreatePaymentRecipientResponse\x12c\n" +
	"\x14GetPaymentRecipients\x12$.payment.GetPaymentRecipientsRequest\x1a%.payment.GetPaymentRecipientsResponse\x12i\n" +
	"\x16UpdatePaymentRecipient\x12&.payment.UpdatePaymentRecipientRequest\x1a'.payment.UpdatePaymentRecipientResponse\x12i\n" +
	"\x16DeletePaymentRecipient\x12&.payment.DeletePaymentRecipientRequest\x1a'.payment.DeletePaymentRecipientResponse\x12o\n" +
	"\x18ReorderPaymentRecipients\x12(.payment.ReorderPaymentRecipientsRequest\x1a).payment.ReorderPaymentRecipientsResponse\x12K\n" +
	"\fGetTransfers\x12\x1c.payment.GetTransfersRequest\x1a\x1d.payment.GetTransfersResponseB<Z:github.com/RAF-SI-2025/EXBanka-4-Backend/shared/pb/paymentb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_payment_proto_goTypes = []any{
	(*CreatePaymentRequest)(nil),             // 0: payment.CreatePaymentRequest
	(*CreatePaymentResponse)(nil),            // 1: payment.CreatePaymentResponse
	(*PaymentRecipient)(nil),                 // 2: payment.PaymentRecipient
	(*ReorderPaymentRecipientsRequest)(nil),  // 3: payment.ReorderPaymentRecipientsRequest
	(*ReorderPaymentRecipientsResponse)(nil), // 4: payment.ReorderPaymentRecipientsResponse
	(*CreatePaymentRecipientRequest)(nil),    // 5: payment.CreatePaymentRecipientRequest
	(*CreatePaymentRecipientResponse)(nil),   // 6: payment.CreatePaymentRecipientResponse
	(*GetPaymentRecipientsRequest)(nil),      // 7: payment.GetPaymentRecipientsRequest
	(*GetPaymentRecipientsResponse)(nil),     // 8: payment.GetPaymentRecipientsResponse
	(*DeletePaymentRecipientRequest)(nil),    // 9: payment.DeletePaymentRecipientRequest
	(*DeletePaymentRecipientResponse)(nil),   // 10: payment.DeletePaymentRecipientResponse
	(*UpdatePaymentRecipientRequest)(nil),    // 11: payment.UpdatePaymentRecipientRequest
	(*UpdatePaymentRecipientResponse)(nil),   // 12: payment.UpdatePaymentRecipientResponse
	(*Payment)(nil),                          // 13: payment.Payment
	(*GetPaymentByIdRequest)(nil),            // 14: payment.GetPaymentByIdRequest
	(*GetPaymentByIdResponse)(nil),           // 15: payment.GetPaymentByIdResponse
	(*GetPaymentsRequest)(nil),               // 16: payment.GetPaymentsRequest
	(*GetPaymentsResponse)(nil),              // 17: payment.GetPaymentsResponse
	(*CreateTransferRequest)(nil),            // 18: payment.CreateTransferRequest
	(*CreateTransferResponse)(nil),           // 19: payment.CreateTransferResponse
	(*Transfer)(nil),                         // 20: payment.Transfer
	(*GetTransfersRequest)(nil),              // 21: payment.GetTransfersRequest
	(*GetTransfersResponse)(nil),             // 22: payment.GetTransfersResponse
}
var file_payment_proto_depIdxs = []int32{
	2,  // 0: payment.CreatePaymentRecipientResponse.recipient:type_name -> payment.PaymentRecipient
	2,  // 1: payment.GetPaymentRecipientsResponse.recipients:type_name -> payment.PaymentRecipient
	2,  // 2: payment.UpdatePaymentRecipientResponse.recipient:type_name -> payment.PaymentRecipient
	13, // 3: payment.GetPaymentByIdResponse.payment:type_name -> payment.Payment
	13, // 4: payment.GetPaymentsResponse.payments:type_name -> payment.Payment
	20, // 5: payment.GetTransfersResponse.transfers:type_name -> payment.Transfer
	0,  // 6: payment.PaymentService.CreatePayment:input_type -> payment.CreatePaymentRequest
	16, // 7: payment.PaymentService.GetPayments:input_type -> payment.GetPaymentsRequest
	14, // 8: payment.PaymentService.GetPaymentById:input_type -> payment.GetPaymentByIdRequest
	18, // 9: payment.PaymentService.CreateTransfer:input_type -> payment.CreateTransferRequest
	5,  // 10: payment.PaymentService.CreatePaymentRecipient:input_type -> payment.CreatePaymentRecipientRequest
	7,  // 11: payment.PaymentService.GetPaymentRecipients:input_type -> payment.GetPaymentRecipientsRequest
	11, // 12: payment.PaymentService.UpdatePaymentRecipient:input_type -> payment.UpdatePaymentRecipientRequest
	9,  // 13: payment.PaymentService.DeletePaymentRecipient:input_type -> payment.DeletePaymentRecipientRequest
	3,  // 14: payment.PaymentService.ReorderPaymentRecipients:input_type -> payment.ReorderPaymentRecipientsRequest
	21, // 15: payment.PaymentService.GetTransfers:input_type -> payment.GetTransfersRequest
	1,  // 16: payment.PaymentService.CreatePayment:output_type -> payment.CreatePaymentResponse
	17, // 17: payment.PaymentService.GetPayments:output_type -> payment.GetPaymentsResponse
	15, // 18: payment.PaymentService.GetPaymentById:output_type -> payment.GetPaymentByIdResponse
	19, // 19: payment.PaymentService.CreateTransfer:output_type -> payment.CreateTransferResponse
	6,  // 20: payment.PaymentService.CreatePaymentRecipient:output_type -> payment.CreatePaymentRecipientResponse
	8,  // 21: payment.PaymentService.GetPaymentRecipients:output_type -> payment.GetPaymentRecipientsResponse
	12, // 22: payment.PaymentService.UpdatePaymentRecipient:output_type -> payment.UpdatePaymentRecipientResponse
	10, // 23: payment.PaymentService.DeletePaymentRecipient:output_type -> payment.DeletePaymentRecipientResponse
	4,  // 24: payment.PaymentService.ReorderPaymentRecipients:output_type -> payment.ReorderPaymentRecipientsResponse
	22, // 25: payment.PaymentService.GetTransfers:output_type -> payment.GetTransfersResponse
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
