// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.0
// source: account.proto

package account

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompanyData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RegistrationNumber string                 `protobuf:"bytes,2,opt,name=registration_number,json=registrationNumber,proto3" json:"registration_number,omitempty"`
	Pib                string                 `protobuf:"bytes,3,opt,name=pib,proto3" json:"pib,omitempty"`
	ActivityCode       string                 `protobuf:"bytes,4,opt,name=activity_code,json=activityCode,proto3" json:"activity_code,omitempty"`
	Address            string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CompanyData) Reset() {
	*x = CompanyData{}
	mi := &file_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyData) ProtoMessage() {}

func (x *CompanyData) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyData.ProtoReflect.Descriptor instead.
func (*CompanyData) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{0}
}

func (x *CompanyData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompanyData) GetRegistrationNumber() string {
	if x != nil {
		return x.RegistrationNumber
	}
	return ""
}

func (x *CompanyData) GetPib() string {
	if x != nil {
		return x.Pib
	}
	return ""
}

func (x *CompanyData) GetActivityCode() string {
	if x != nil {
		return x.ActivityCode
	}
	return ""
}

func (x *CompanyData) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateAccountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientId       int64                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AccountType    string                 `protobuf:"bytes,2,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	CurrencyCode   string                 `protobuf:"bytes,3,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	InitialBalance float64                `protobuf:"fixed64,4,opt,name=initial_balance,json=initialBalance,proto3" json:"initial_balance,omitempty"`
	AccountName    string                 `protobuf:"bytes,5,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	CreateCard     bool                   `protobuf:"varint,6,opt,name=create_card,json=createCard,proto3" json:"create_card,omitempty"`
	EmployeeId     int64                  `protobuf:"varint,7,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	CompanyData    *CompanyData           `protobuf:"bytes,8,opt,name=company_data,json=companyData,proto3" json:"company_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *CreateAccountRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *CreateAccountRequest) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *CreateAccountRequest) GetInitialBalance() float64 {
	if x != nil {
		return x.InitialBalance
	}
	return 0
}

func (x *CreateAccountRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *CreateAccountRequest) GetCreateCard() bool {
	if x != nil {
		return x.CreateCard
	}
	return false
}

func (x *CreateAccountRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *CreateAccountRequest) GetCompanyData() *CompanyData {
	if x != nil {
		return x.CompanyData
	}
	return nil
}

type AccountResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountNumber    string                 `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	AccountName      string                 `protobuf:"bytes,3,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	OwnerId          int64                  `protobuf:"varint,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	EmployeeId       int64                  `protobuf:"varint,5,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	CurrencyCode     string                 `protobuf:"bytes,6,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	AccountType      string                 `protobuf:"bytes,7,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Status           string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Balance          float64                `protobuf:"fixed64,9,opt,name=balance,proto3" json:"balance,omitempty"`
	AvailableBalance float64                `protobuf:"fixed64,10,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	CreatedDate      string                 `protobuf:"bytes,11,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AccountResponse) Reset() {
	*x = AccountResponse{}
	mi := &file_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountResponse) ProtoMessage() {}

func (x *AccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountResponse.ProtoReflect.Descriptor instead.
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2}
}

func (x *AccountResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AccountResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *AccountResponse) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *AccountResponse) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *AccountResponse) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *AccountResponse) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *AccountResponse) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *AccountResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AccountResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *AccountResponse) GetAvailableBalance() float64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *AccountResponse) GetCreatedDate() string {
	if x != nil {
		return x.CreatedDate
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *AccountResponse       `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountResponse) GetAccount() *AccountResponse {
	if x != nil {
		return x.Account
	}
	return nil
}

var File_account_proto protoreflect.FileDescriptor

const file_account_proto_rawDesc = "" +
	"\n" +
	"\raccount.proto\x12\aaccount\"\xa3\x01\n" +
	"\vCompanyData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\x13registration_number\x18\x02 \x01(\tR\x12registrationNumber\x12\x10\n" +
	"\x03pib\x18\x03 \x01(\tR\x03pib\x12#\n" +
	"\ractivity_code\x18\x04 \x01(\tR\factivityCode\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\"\xc2\x02\n" +
	"\x14CreateAccountRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x03R\bclientId\x12!\n" +
	"\faccount_type\x18\x02 \x01(\tR\vaccountType\x12#\n" +
	"\rcurrency_code\x18\x03 \x01(\tR\fcurrencyCode\x12'\n" +
	"\x0finitial_balance\x18\x04 \x01(\x01R\x0einitialBalance\x12!\n" +
	"\faccount_name\x18\x05 \x01(\tR\vaccountName\x12\x1f\n" +
	"\vcreate_card\x18\x06 \x01(\bR\n" +
	"createCard\x12\x1f\n" +
	"\vemployee_id\x18\a \x01(\x03R\n" +
	"employeeId\x127\n" +
	"\fcompany_data\x18\b \x01(\v2\x14.account.CompanyDataR\vcompanyData\"\xf1\x02\n" +
	"\x0fAccountResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\x12!\n" +
	"\faccount_name\x18\x03 \x01(\tR\vaccountName\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\x03R\aownerId\x12\x1f\n" +
	"\vemployee_id\x18\x05 \x01(\x03R\n" +
	"employeeId\x12#\n" +
	"\rcurrency_code\x18\x06 \x01(\tR\fcurrencyCode\x12!\n" +
	"\faccount_type\x18\a \x01(\tR\vaccountType\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x18\n" +
	"\abalance\x18\t \x01(\x01R\abalance\x12+\n" +
	"\x11available_balance\x18\n" +
	" \x01(\x01R\x10availableBalance\x12!\n" +
	"\fcreated_date\x18\v \x01(\tR\vcreatedDate\"K\n" +
	"\x15CreateAccountResponse\x122\n" +
	"\aaccount\x18\x01 \x01(\v2\x18.account.AccountResponseR\aaccount2`\n" +
	"\x0eAccountService\x12N\n" +
	"\rCreateAccount\x12\x1d.account.CreateAccountRequest\x1a\x1e.account.CreateAccountResponseB<Z:github.com/RAF-SI-2025/EXBanka-4-Backend/shared/pb/accountb\x06proto3"

var (
	file_account_proto_rawDescOnce sync.Once
	file_account_proto_rawDescData []byte
)

func file_account_proto_rawDescGZIP() []byte {
	file_account_proto_rawDescOnce.Do(func() {
		file_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)))
	})
	return file_account_proto_rawDescData
}

var file_account_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_account_proto_goTypes = []any{
	(*CompanyData)(nil),           // 0: account.CompanyData
	(*CreateAccountRequest)(nil),  // 1: account.CreateAccountRequest
	(*AccountResponse)(nil),       // 2: account.AccountResponse
	(*CreateAccountResponse)(nil), // 3: account.CreateAccountResponse
}
var file_account_proto_depIdxs = []int32{
	0, // 0: account.CreateAccountRequest.company_data:type_name -> account.CompanyData
	2, // 1: account.CreateAccountResponse.account:type_name -> account.AccountResponse
	1, // 2: account.AccountService.CreateAccount:input_type -> account.CreateAccountRequest
	3, // 3: account.AccountService.CreateAccount:output_type -> account.CreateAccountResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_account_proto_init() }
func file_account_proto_init() {
	if File_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_proto_goTypes,
		DependencyIndexes: file_account_proto_depIdxs,
		MessageInfos:      file_account_proto_msgTypes,
	}.Build()
	File_account_proto = out.File
	file_account_proto_goTypes = nil
	file_account_proto_depIdxs = nil
}
