// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: securities.proto

package securities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_securities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_securities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StockExchange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Acronym       string                 `protobuf:"bytes,3,opt,name=acronym,proto3" json:"acronym,omitempty"`
	MicCode       string                 `protobuf:"bytes,4,opt,name=mic_code,json=micCode,proto3" json:"mic_code,omitempty"`
	Polity        string                 `protobuf:"bytes,5,opt,name=polity,proto3" json:"polity,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Timezone      string                 `protobuf:"bytes,7,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockExchange) Reset() {
	*x = StockExchange{}
	mi := &file_securities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockExchange) ProtoMessage() {}

func (x *StockExchange) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockExchange.ProtoReflect.Descriptor instead.
func (*StockExchange) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{2}
}

func (x *StockExchange) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StockExchange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StockExchange) GetAcronym() string {
	if x != nil {
		return x.Acronym
	}
	return ""
}

func (x *StockExchange) GetMicCode() string {
	if x != nil {
		return x.MicCode
	}
	return ""
}

func (x *StockExchange) GetPolity() string {
	if x != nil {
		return x.Polity
	}
	return ""
}

func (x *StockExchange) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *StockExchange) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type GetStockExchangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 1-based, default 1
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // default 10
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockExchangesRequest) Reset() {
	*x = GetStockExchangesRequest{}
	mi := &file_securities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockExchangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockExchangesRequest) ProtoMessage() {}

func (x *GetStockExchangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockExchangesRequest.ProtoReflect.Descriptor instead.
func (*GetStockExchangesRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{3}
}

func (x *GetStockExchangesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetStockExchangesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetStockExchangesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchanges     []*StockExchange       `protobuf:"bytes,1,rep,name=exchanges,proto3" json:"exchanges,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockExchangesResponse) Reset() {
	*x = GetStockExchangesResponse{}
	mi := &file_securities_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockExchangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockExchangesResponse) ProtoMessage() {}

func (x *GetStockExchangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockExchangesResponse.ProtoReflect.Descriptor instead.
func (*GetStockExchangesResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{4}
}

func (x *GetStockExchangesResponse) GetExchanges() []*StockExchange {
	if x != nil {
		return x.Exchanges
	}
	return nil
}

func (x *GetStockExchangesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetStockExchangeByMICRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MicCode       string                 `protobuf:"bytes,1,opt,name=mic_code,json=micCode,proto3" json:"mic_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockExchangeByMICRequest) Reset() {
	*x = GetStockExchangeByMICRequest{}
	mi := &file_securities_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockExchangeByMICRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockExchangeByMICRequest) ProtoMessage() {}

func (x *GetStockExchangeByMICRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockExchangeByMICRequest.ProtoReflect.Descriptor instead.
func (*GetStockExchangeByMICRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{5}
}

func (x *GetStockExchangeByMICRequest) GetMicCode() string {
	if x != nil {
		return x.MicCode
	}
	return ""
}

type GetStockExchangeByMICResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      *StockExchange         `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockExchangeByMICResponse) Reset() {
	*x = GetStockExchangeByMICResponse{}
	mi := &file_securities_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockExchangeByMICResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockExchangeByMICResponse) ProtoMessage() {}

func (x *GetStockExchangeByMICResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockExchangeByMICResponse.ProtoReflect.Descriptor instead.
func (*GetStockExchangeByMICResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{6}
}

func (x *GetStockExchangeByMICResponse) GetExchange() *StockExchange {
	if x != nil {
		return x.Exchange
	}
	return nil
}

type GetStockExchangeByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockExchangeByIdRequest) Reset() {
	*x = GetStockExchangeByIdRequest{}
	mi := &file_securities_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockExchangeByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockExchangeByIdRequest) ProtoMessage() {}

func (x *GetStockExchangeByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockExchangeByIdRequest.ProtoReflect.Descriptor instead.
func (*GetStockExchangeByIdRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{7}
}

func (x *GetStockExchangeByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetStockExchangeByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      *StockExchange         `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockExchangeByIdResponse) Reset() {
	*x = GetStockExchangeByIdResponse{}
	mi := &file_securities_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockExchangeByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockExchangeByIdResponse) ProtoMessage() {}

func (x *GetStockExchangeByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockExchangeByIdResponse.ProtoReflect.Descriptor instead.
func (*GetStockExchangeByIdResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{8}
}

func (x *GetStockExchangeByIdResponse) GetExchange() *StockExchange {
	if x != nil {
		return x.Exchange
	}
	return nil
}

type CreateStockExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Acronym       string                 `protobuf:"bytes,2,opt,name=acronym,proto3" json:"acronym,omitempty"`
	MicCode       string                 `protobuf:"bytes,3,opt,name=mic_code,json=micCode,proto3" json:"mic_code,omitempty"`
	Polity        string                 `protobuf:"bytes,4,opt,name=polity,proto3" json:"polity,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Timezone      string                 `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStockExchangeRequest) Reset() {
	*x = CreateStockExchangeRequest{}
	mi := &file_securities_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStockExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStockExchangeRequest) ProtoMessage() {}

func (x *CreateStockExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStockExchangeRequest.ProtoReflect.Descriptor instead.
func (*CreateStockExchangeRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{9}
}

func (x *CreateStockExchangeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateStockExchangeRequest) GetAcronym() string {
	if x != nil {
		return x.Acronym
	}
	return ""
}

func (x *CreateStockExchangeRequest) GetMicCode() string {
	if x != nil {
		return x.MicCode
	}
	return ""
}

func (x *CreateStockExchangeRequest) GetPolity() string {
	if x != nil {
		return x.Polity
	}
	return ""
}

func (x *CreateStockExchangeRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateStockExchangeRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type CreateStockExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      *StockExchange         `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStockExchangeResponse) Reset() {
	*x = CreateStockExchangeResponse{}
	mi := &file_securities_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStockExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStockExchangeResponse) ProtoMessage() {}

func (x *CreateStockExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStockExchangeResponse.ProtoReflect.Descriptor instead.
func (*CreateStockExchangeResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{10}
}

func (x *CreateStockExchangeResponse) GetExchange() *StockExchange {
	if x != nil {
		return x.Exchange
	}
	return nil
}

type UpdateStockExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MicCode       string                 `protobuf:"bytes,1,opt,name=mic_code,json=micCode,proto3" json:"mic_code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Acronym       string                 `protobuf:"bytes,3,opt,name=acronym,proto3" json:"acronym,omitempty"`
	Polity        string                 `protobuf:"bytes,4,opt,name=polity,proto3" json:"polity,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Timezone      string                 `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockExchangeRequest) Reset() {
	*x = UpdateStockExchangeRequest{}
	mi := &file_securities_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockExchangeRequest) ProtoMessage() {}

func (x *UpdateStockExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockExchangeRequest.ProtoReflect.Descriptor instead.
func (*UpdateStockExchangeRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateStockExchangeRequest) GetMicCode() string {
	if x != nil {
		return x.MicCode
	}
	return ""
}

func (x *UpdateStockExchangeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateStockExchangeRequest) GetAcronym() string {
	if x != nil {
		return x.Acronym
	}
	return ""
}

func (x *UpdateStockExchangeRequest) GetPolity() string {
	if x != nil {
		return x.Polity
	}
	return ""
}

func (x *UpdateStockExchangeRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateStockExchangeRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type UpdateStockExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      *StockExchange         `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockExchangeResponse) Reset() {
	*x = UpdateStockExchangeResponse{}
	mi := &file_securities_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockExchangeResponse) ProtoMessage() {}

func (x *UpdateStockExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockExchangeResponse.ProtoReflect.Descriptor instead.
func (*UpdateStockExchangeResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateStockExchangeResponse) GetExchange() *StockExchange {
	if x != nil {
		return x.Exchange
	}
	return nil
}

type DeleteStockExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MicCode       string                 `protobuf:"bytes,1,opt,name=mic_code,json=micCode,proto3" json:"mic_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStockExchangeRequest) Reset() {
	*x = DeleteStockExchangeRequest{}
	mi := &file_securities_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStockExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStockExchangeRequest) ProtoMessage() {}

func (x *DeleteStockExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStockExchangeRequest.ProtoReflect.Descriptor instead.
func (*DeleteStockExchangeRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteStockExchangeRequest) GetMicCode() string {
	if x != nil {
		return x.MicCode
	}
	return ""
}

type DeleteStockExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStockExchangeResponse) Reset() {
	*x = DeleteStockExchangeResponse{}
	mi := &file_securities_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStockExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStockExchangeResponse) ProtoMessage() {}

func (x *DeleteStockExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStockExchangeResponse.ProtoReflect.Descriptor instead.
func (*DeleteStockExchangeResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{14}
}

type ExchangeWorkingHours struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Polity        string                 `protobuf:"bytes,2,opt,name=polity,proto3" json:"polity,omitempty"`
	Segment       string                 `protobuf:"bytes,3,opt,name=segment,proto3" json:"segment,omitempty"`
	OpenTime      string                 `protobuf:"bytes,4,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	CloseTime     string                 `protobuf:"bytes,5,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeWorkingHours) Reset() {
	*x = ExchangeWorkingHours{}
	mi := &file_securities_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeWorkingHours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeWorkingHours) ProtoMessage() {}

func (x *ExchangeWorkingHours) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeWorkingHours.ProtoReflect.Descriptor instead.
func (*ExchangeWorkingHours) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{15}
}

func (x *ExchangeWorkingHours) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExchangeWorkingHours) GetPolity() string {
	if x != nil {
		return x.Polity
	}
	return ""
}

func (x *ExchangeWorkingHours) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

func (x *ExchangeWorkingHours) GetOpenTime() string {
	if x != nil {
		return x.OpenTime
	}
	return ""
}

func (x *ExchangeWorkingHours) GetCloseTime() string {
	if x != nil {
		return x.CloseTime
	}
	return ""
}

type GetWorkingHoursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MicCode       string                 `protobuf:"bytes,1,opt,name=mic_code,json=micCode,proto3" json:"mic_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkingHoursRequest) Reset() {
	*x = GetWorkingHoursRequest{}
	mi := &file_securities_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkingHoursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkingHoursRequest) ProtoMessage() {}

func (x *GetWorkingHoursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkingHoursRequest.ProtoReflect.Descriptor instead.
func (*GetWorkingHoursRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{16}
}

func (x *GetWorkingHoursRequest) GetMicCode() string {
	if x != nil {
		return x.MicCode
	}
	return ""
}

type GetWorkingHoursResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Hours         []*ExchangeWorkingHours `protobuf:"bytes,1,rep,name=hours,proto3" json:"hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkingHoursResponse) Reset() {
	*x = GetWorkingHoursResponse{}
	mi := &file_securities_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkingHoursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkingHoursResponse) ProtoMessage() {}

func (x *GetWorkingHoursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkingHoursResponse.ProtoReflect.Descriptor instead.
func (*GetWorkingHoursResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{17}
}

func (x *GetWorkingHoursResponse) GetHours() []*ExchangeWorkingHours {
	if x != nil {
		return x.Hours
	}
	return nil
}

type SetWorkingHoursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Polity        string                 `protobuf:"bytes,1,opt,name=polity,proto3" json:"polity,omitempty"`
	Segment       string                 `protobuf:"bytes,2,opt,name=segment,proto3" json:"segment,omitempty"`
	OpenTime      string                 `protobuf:"bytes,3,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	CloseTime     string                 `protobuf:"bytes,4,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWorkingHoursRequest) Reset() {
	*x = SetWorkingHoursRequest{}
	mi := &file_securities_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWorkingHoursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWorkingHoursRequest) ProtoMessage() {}

func (x *SetWorkingHoursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWorkingHoursRequest.ProtoReflect.Descriptor instead.
func (*SetWorkingHoursRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{18}
}

func (x *SetWorkingHoursRequest) GetPolity() string {
	if x != nil {
		return x.Polity
	}
	return ""
}

func (x *SetWorkingHoursRequest) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

func (x *SetWorkingHoursRequest) GetOpenTime() string {
	if x != nil {
		return x.OpenTime
	}
	return ""
}

func (x *SetWorkingHoursRequest) GetCloseTime() string {
	if x != nil {
		return x.CloseTime
	}
	return ""
}

type SetWorkingHoursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hours         *ExchangeWorkingHours  `protobuf:"bytes,1,opt,name=hours,proto3" json:"hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWorkingHoursResponse) Reset() {
	*x = SetWorkingHoursResponse{}
	mi := &file_securities_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWorkingHoursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWorkingHoursResponse) ProtoMessage() {}

func (x *SetWorkingHoursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWorkingHoursResponse.ProtoReflect.Descriptor instead.
func (*SetWorkingHoursResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{19}
}

func (x *SetWorkingHoursResponse) GetHours() *ExchangeWorkingHours {
	if x != nil {
		return x.Hours
	}
	return nil
}

type ExchangeHoliday struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Polity        string                 `protobuf:"bytes,2,opt,name=polity,proto3" json:"polity,omitempty"`
	HolidayDate   string                 `protobuf:"bytes,3,opt,name=holiday_date,json=holidayDate,proto3" json:"holiday_date,omitempty"` // "YYYY-MM-DD"
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeHoliday) Reset() {
	*x = ExchangeHoliday{}
	mi := &file_securities_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeHoliday) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeHoliday) ProtoMessage() {}

func (x *ExchangeHoliday) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeHoliday.ProtoReflect.Descriptor instead.
func (*ExchangeHoliday) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{20}
}

func (x *ExchangeHoliday) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExchangeHoliday) GetPolity() string {
	if x != nil {
		return x.Polity
	}
	return ""
}

func (x *ExchangeHoliday) GetHolidayDate() string {
	if x != nil {
		return x.HolidayDate
	}
	return ""
}

func (x *ExchangeHoliday) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetHolidaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Polity        string                 `protobuf:"bytes,1,opt,name=polity,proto3" json:"polity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHolidaysRequest) Reset() {
	*x = GetHolidaysRequest{}
	mi := &file_securities_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHolidaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHolidaysRequest) ProtoMessage() {}

func (x *GetHolidaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHolidaysRequest.ProtoReflect.Descriptor instead.
func (*GetHolidaysRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{21}
}

func (x *GetHolidaysRequest) GetPolity() string {
	if x != nil {
		return x.Polity
	}
	return ""
}

type GetHolidaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holidays      []*ExchangeHoliday     `protobuf:"bytes,1,rep,name=holidays,proto3" json:"holidays,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHolidaysResponse) Reset() {
	*x = GetHolidaysResponse{}
	mi := &file_securities_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHolidaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHolidaysResponse) ProtoMessage() {}

func (x *GetHolidaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHolidaysResponse.ProtoReflect.Descriptor instead.
func (*GetHolidaysResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{22}
}

func (x *GetHolidaysResponse) GetHolidays() []*ExchangeHoliday {
	if x != nil {
		return x.Holidays
	}
	return nil
}

type AddHolidayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Polity        string                 `protobuf:"bytes,1,opt,name=polity,proto3" json:"polity,omitempty"`
	HolidayDate   string                 `protobuf:"bytes,2,opt,name=holiday_date,json=holidayDate,proto3" json:"holiday_date,omitempty"` // "YYYY-MM-DD"
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddHolidayRequest) Reset() {
	*x = AddHolidayRequest{}
	mi := &file_securities_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddHolidayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHolidayRequest) ProtoMessage() {}

func (x *AddHolidayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHolidayRequest.ProtoReflect.Descriptor instead.
func (*AddHolidayRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{23}
}

func (x *AddHolidayRequest) GetPolity() string {
	if x != nil {
		return x.Polity
	}
	return ""
}

func (x *AddHolidayRequest) GetHolidayDate() string {
	if x != nil {
		return x.HolidayDate
	}
	return ""
}

func (x *AddHolidayRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AddHolidayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holiday       *ExchangeHoliday       `protobuf:"bytes,1,opt,name=holiday,proto3" json:"holiday,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddHolidayResponse) Reset() {
	*x = AddHolidayResponse{}
	mi := &file_securities_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddHolidayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHolidayResponse) ProtoMessage() {}

func (x *AddHolidayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHolidayResponse.ProtoReflect.Descriptor instead.
func (*AddHolidayResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{24}
}

func (x *AddHolidayResponse) GetHoliday() *ExchangeHoliday {
	if x != nil {
		return x.Holiday
	}
	return nil
}

type DeleteHolidayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Polity        string                 `protobuf:"bytes,1,opt,name=polity,proto3" json:"polity,omitempty"`
	HolidayDate   string                 `protobuf:"bytes,2,opt,name=holiday_date,json=holidayDate,proto3" json:"holiday_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHolidayRequest) Reset() {
	*x = DeleteHolidayRequest{}
	mi := &file_securities_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHolidayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHolidayRequest) ProtoMessage() {}

func (x *DeleteHolidayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHolidayRequest.ProtoReflect.Descriptor instead.
func (*DeleteHolidayRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteHolidayRequest) GetPolity() string {
	if x != nil {
		return x.Polity
	}
	return ""
}

func (x *DeleteHolidayRequest) GetHolidayDate() string {
	if x != nil {
		return x.HolidayDate
	}
	return ""
}

type DeleteHolidayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHolidayResponse) Reset() {
	*x = DeleteHolidayResponse{}
	mi := &file_securities_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHolidayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHolidayResponse) ProtoMessage() {}

func (x *DeleteHolidayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHolidayResponse.ProtoReflect.Descriptor instead.
func (*DeleteHolidayResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{26}
}

type IsExchangeOpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MicCode       string                 `protobuf:"bytes,1,opt,name=mic_code,json=micCode,proto3" json:"mic_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsExchangeOpenRequest) Reset() {
	*x = IsExchangeOpenRequest{}
	mi := &file_securities_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsExchangeOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsExchangeOpenRequest) ProtoMessage() {}

func (x *IsExchangeOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsExchangeOpenRequest.ProtoReflect.Descriptor instead.
func (*IsExchangeOpenRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{27}
}

func (x *IsExchangeOpenRequest) GetMicCode() string {
	if x != nil {
		return x.MicCode
	}
	return ""
}

type IsExchangeOpenResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MicCode          string                 `protobuf:"bytes,1,opt,name=mic_code,json=micCode,proto3" json:"mic_code,omitempty"`
	IsOpen           bool                   `protobuf:"varint,2,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	Segment          string                 `protobuf:"bytes,3,opt,name=segment,proto3" json:"segment,omitempty"`                                             // "pre_market", "regular", "post_market", "test_mode", or "closed"
	CurrentTimeLocal string                 `protobuf:"bytes,4,opt,name=current_time_local,json=currentTimeLocal,proto3" json:"current_time_local,omitempty"` // "HH:MM" in exchange's local timezone
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IsExchangeOpenResponse) Reset() {
	*x = IsExchangeOpenResponse{}
	mi := &file_securities_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsExchangeOpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsExchangeOpenResponse) ProtoMessage() {}

func (x *IsExchangeOpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsExchangeOpenResponse.ProtoReflect.Descriptor instead.
func (*IsExchangeOpenResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{28}
}

func (x *IsExchangeOpenResponse) GetMicCode() string {
	if x != nil {
		return x.MicCode
	}
	return ""
}

func (x *IsExchangeOpenResponse) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

func (x *IsExchangeOpenResponse) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

func (x *IsExchangeOpenResponse) GetCurrentTimeLocal() string {
	if x != nil {
		return x.CurrentTimeLocal
	}
	return ""
}

type GetTestModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTestModeRequest) Reset() {
	*x = GetTestModeRequest{}
	mi := &file_securities_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTestModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestModeRequest) ProtoMessage() {}

func (x *GetTestModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestModeRequest.ProtoReflect.Descriptor instead.
func (*GetTestModeRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{29}
}

type GetTestModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTestModeResponse) Reset() {
	*x = GetTestModeResponse{}
	mi := &file_securities_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTestModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestModeResponse) ProtoMessage() {}

func (x *GetTestModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestModeResponse.ProtoReflect.Descriptor instead.
func (*GetTestModeResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{30}
}

func (x *GetTestModeResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SetTestModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTestModeRequest) Reset() {
	*x = SetTestModeRequest{}
	mi := &file_securities_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTestModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTestModeRequest) ProtoMessage() {}

func (x *SetTestModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTestModeRequest.ProtoReflect.Descriptor instead.
func (*SetTestModeRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{31}
}

func (x *SetTestModeRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SetTestModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTestModeResponse) Reset() {
	*x = SetTestModeResponse{}
	mi := &file_securities_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTestModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTestModeResponse) ProtoMessage() {}

func (x *SetTestModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTestModeResponse.ProtoReflect.Descriptor instead.
func (*SetTestModeResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{32}
}

func (x *SetTestModeResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

var File_securities_proto protoreflect.FileDescriptor

const file_securities_proto_rawDesc = "" +
	"\n" +
	"\x10securities.proto\x12\n" +
	"securities\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xb8\x01\n" +
	"\rStockExchange\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aacronym\x18\x03 \x01(\tR\aacronym\x12\x19\n" +
	"\bmic_code\x18\x04 \x01(\tR\amicCode\x12\x16\n" +
	"\x06polity\x18\x05 \x01(\tR\x06polity\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x1a\n" +
	"\btimezone\x18\a \x01(\tR\btimezone\"K\n" +
	"\x18GetStockExchangesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"u\n" +
	"\x19GetStockExchangesResponse\x127\n" +
	"\texchanges\x18\x01 \x03(\v2\x19.securities.StockExchangeR\texchanges\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"9\n" +
	"\x1cGetStockExchangeByMICRequest\x12\x19\n" +
	"\bmic_code\x18\x01 \x01(\tR\amicCode\"V\n" +
	"\x1dGetStockExchangeByMICResponse\x125\n" +
	"\bexchange\x18\x01 \x01(\v2\x19.securities.StockExchangeR\bexchange\"-\n" +
	"\x1bGetStockExchangeByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"U\n" +
	"\x1cGetStockExchangeByIdResponse\x125\n" +
	"\bexchange\x18\x01 \x01(\v2\x19.securities.StockExchangeR\bexchange\"\xb5\x01\n" +
	"\x1aCreateStockExchangeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aacronym\x18\x02 \x01(\tR\aacronym\x12\x19\n" +
	"\bmic_code\x18\x03 \x01(\tR\amicCode\x12\x16\n" +
	"\x06polity\x18\x04 \x01(\tR\x06polity\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1a\n" +
	"\btimezone\x18\x06 \x01(\tR\btimezone\"T\n" +
	"\x1bCreateStockExchangeResponse\x125\n" +
	"\bexchange\x18\x01 \x01(\v2\x19.securities.StockExchangeR\bexchange\"\xb5\x01\n" +
	"\x1aUpdateStockExchangeRequest\x12\x19\n" +
	"\bmic_code\x18\x01 \x01(\tR\amicCode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aacronym\x18\x03 \x01(\tR\aacronym\x12\x16\n" +
	"\x06polity\x18\x04 \x01(\tR\x06polity\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1a\n" +
	"\btimezone\x18\x06 \x01(\tR\btimezone\"T\n" +
	"\x1bUpdateStockExchangeResponse\x125\n" +
	"\bexchange\x18\x01 \x01(\v2\x19.securities.StockExchangeR\bexchange\"7\n" +
	"\x1aDeleteStockExchangeRequest\x12\x19\n" +
	"\bmic_code\x18\x01 \x01(\tR\amicCode\"\x1d\n" +
	"\x1bDeleteStockExchangeResponse\"\x94\x01\n" +
	"\x14ExchangeWorkingHours\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06polity\x18\x02 \x01(\tR\x06polity\x12\x18\n" +
	"\asegment\x18\x03 \x01(\tR\asegment\x12\x1b\n" +
	"\topen_time\x18\x04 \x01(\tR\bopenTime\x12\x1d\n" +
	"\n" +
	"close_time\x18\x05 \x01(\tR\tcloseTime\"3\n" +
	"\x16GetWorkingHoursRequest\x12\x19\n" +
	"\bmic_code\x18\x01 \x01(\tR\amicCode\"Q\n" +
	"\x17GetWorkingHoursResponse\x126\n" +
	"\x05hours\x18\x01 \x03(\v2 .securities.ExchangeWorkingHoursR\x05hours\"\x86\x01\n" +
	"\x16SetWorkingHoursRequest\x12\x16\n" +
	"\x06polity\x18\x01 \x01(\tR\x06polity\x12\x18\n" +
	"\asegment\x18\x02 \x01(\tR\asegment\x12\x1b\n" +
	"\topen_time\x18\x03 \x01(\tR\bopenTime\x12\x1d\n" +
	"\n" +
	"close_time\x18\x04 \x01(\tR\tcloseTime\"Q\n" +
	"\x17SetWorkingHoursResponse\x126\n" +
	"\x05hours\x18\x01 \x01(\v2 .securities.ExchangeWorkingHoursR\x05hours\"~\n" +
	"\x0fExchangeHoliday\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06polity\x18\x02 \x01(\tR\x06polity\x12!\n" +
	"\fholiday_date\x18\x03 \x01(\tR\vholidayDate\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\",\n" +
	"\x12GetHolidaysRequest\x12\x16\n" +
	"\x06polity\x18\x01 \x01(\tR\x06polity\"N\n" +
	"\x13GetHolidaysResponse\x127\n" +
	"\bholidays\x18\x01 \x03(\v2\x1b.securities.ExchangeHolidayR\bholidays\"p\n" +
	"\x11AddHolidayRequest\x12\x16\n" +
	"\x06polity\x18\x01 \x01(\tR\x06polity\x12!\n" +
	"\fholiday_date\x18\x02 \x01(\tR\vholidayDate\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"K\n" +
	"\x12AddHolidayResponse\x125\n" +
	"\aholiday\x18\x01 \x01(\v2\x1b.securities.ExchangeHolidayR\aholiday\"Q\n" +
	"\x14DeleteHolidayRequest\x12\x16\n" +
	"\x06polity\x18\x01 \x01(\tR\x06polity\x12!\n" +
	"\fholiday_date\x18\x02 \x01(\tR\vholidayDate\"\x17\n" +
	"\x15DeleteHolidayResponse\"2\n" +
	"\x15IsExchangeOpenRequest\x12\x19\n" +
	"\bmic_code\x18\x01 \x01(\tR\amicCode\"\x94\x01\n" +
	"\x16IsExchangeOpenResponse\x12\x19\n" +
	"\bmic_code\x18\x01 \x01(\tR\amicCode\x12\x17\n" +
	"\ais_open\x18\x02 \x01(\bR\x06isOpen\x12\x18\n" +
	"\asegment\x18\x03 \x01(\tR\asegment\x12,\n" +
	"\x12current_time_local\x18\x04 \x01(\tR\x10currentTimeLocal\"\x14\n" +
	"\x12GetTestModeRequest\"/\n" +
	"\x13GetTestModeResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\".\n" +
	"\x12SetTestModeRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"/\n" +
	"\x13SetTestModeResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled2\xe5\n" +
	"\n" +
	"\x11SecuritiesService\x129\n" +
	"\x04Ping\x12\x17.securities.PingRequest\x1a\x18.securities.PingResponse\x12`\n" +
	"\x11GetStockExchanges\x12$.securities.GetStockExchangesRequest\x1a%.securities.GetStockExchangesResponse\x12l\n" +
	"\x15GetStockExchangeByMIC\x12(.securities.GetStockExchangeByMICRequest\x1a).securities.GetStockExchangeByMICResponse\x12i\n" +
	"\x14GetStockExchangeById\x12'.securities.GetStockExchangeByIdRequest\x1a(.securities.GetStockExchangeByIdResponse\x12f\n" +
	"\x13CreateStockExchange\x12&.securities.CreateStockExchangeRequest\x1a'.securities.CreateStockExchangeResponse\x12f\n" +
	"\x13UpdateStockExchange\x12&.securities.UpdateStockExchangeRequest\x1a'.securities.UpdateStockExchangeResponse\x12f\n" +
	"\x13DeleteStockExchange\x12&.securities.DeleteStockExchangeRequest\x1a'.securities.DeleteStockExchangeResponse\x12Z\n" +
	"\x0fGetWorkingHours\x12\".securities.GetWorkingHoursRequest\x1a#.securities.GetWorkingHoursResponse\x12Z\n" +
	"\x0fSetWorkingHours\x12\".securities.SetWorkingHoursRequest\x1a#.securities.SetWorkingHoursResponse\x12N\n" +
	"\vGetHolidays\x12\x1e.securities.GetHolidaysRequest\x1a\x1f.securities.GetHolidaysResponse\x12K\n" +
	"\n" +
	"AddHoliday\x12\x1d.securities.AddHolidayRequest\x1a\x1e.securities.AddHolidayResponse\x12T\n" +
	"\rDeleteHoliday\x12 .securities.DeleteHolidayRequest\x1a!.securities.DeleteHolidayResponse\x12W\n" +
	"\x0eIsExchangeOpen\x12!.securities.IsExchangeOpenRequest\x1a\".securities.IsExchangeOpenResponse\x12N\n" +
	"\vGetTestMode\x12\x1e.securities.GetTestModeRequest\x1a\x1f.securities.GetTestModeResponse\x12N\n" +
	"\vSetTestMode\x12\x1e.securities.SetTestModeRequest\x1a\x1f.securities.SetTestModeResponseB?Z=github.com/RAF-SI-2025/EXBanka-4-Backend/shared/pb/securitiesb\x06proto3"

var (
	file_securities_proto_rawDescOnce sync.Once
	file_securities_proto_rawDescData []byte
)

func file_securities_proto_rawDescGZIP() []byte {
	file_securities_proto_rawDescOnce.Do(func() {
		file_securities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_securities_proto_rawDesc), len(file_securities_proto_rawDesc)))
	})
	return file_securities_proto_rawDescData
}

var file_securities_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_securities_proto_goTypes = []any{
	(*PingRequest)(nil),                   // 0: securities.PingRequest
	(*PingResponse)(nil),                  // 1: securities.PingResponse
	(*StockExchange)(nil),                 // 2: securities.StockExchange
	(*GetStockExchangesRequest)(nil),      // 3: securities.GetStockExchangesRequest
	(*GetStockExchangesResponse)(nil),     // 4: securities.GetStockExchangesResponse
	(*GetStockExchangeByMICRequest)(nil),  // 5: securities.GetStockExchangeByMICRequest
	(*GetStockExchangeByMICResponse)(nil), // 6: securities.GetStockExchangeByMICResponse
	(*GetStockExchangeByIdRequest)(nil),   // 7: securities.GetStockExchangeByIdRequest
	(*GetStockExchangeByIdResponse)(nil),  // 8: securities.GetStockExchangeByIdResponse
	(*CreateStockExchangeRequest)(nil),    // 9: securities.CreateStockExchangeRequest
	(*CreateStockExchangeResponse)(nil),   // 10: securities.CreateStockExchangeResponse
	(*UpdateStockExchangeRequest)(nil),    // 11: securities.UpdateStockExchangeRequest
	(*UpdateStockExchangeResponse)(nil),   // 12: securities.UpdateStockExchangeResponse
	(*DeleteStockExchangeRequest)(nil),    // 13: securities.DeleteStockExchangeRequest
	(*DeleteStockExchangeResponse)(nil),   // 14: securities.DeleteStockExchangeResponse
	(*ExchangeWorkingHours)(nil),          // 15: securities.ExchangeWorkingHours
	(*GetWorkingHoursRequest)(nil),        // 16: securities.GetWorkingHoursRequest
	(*GetWorkingHoursResponse)(nil),       // 17: securities.GetWorkingHoursResponse
	(*SetWorkingHoursRequest)(nil),        // 18: securities.SetWorkingHoursRequest
	(*SetWorkingHoursResponse)(nil),       // 19: securities.SetWorkingHoursResponse
	(*ExchangeHoliday)(nil),               // 20: securities.ExchangeHoliday
	(*GetHolidaysRequest)(nil),            // 21: securities.GetHolidaysRequest
	(*GetHolidaysResponse)(nil),           // 22: securities.GetHolidaysResponse
	(*AddHolidayRequest)(nil),             // 23: securities.AddHolidayRequest
	(*AddHolidayResponse)(nil),            // 24: securities.AddHolidayResponse
	(*DeleteHolidayRequest)(nil),          // 25: securities.DeleteHolidayRequest
	(*DeleteHolidayResponse)(nil),         // 26: securities.DeleteHolidayResponse
	(*IsExchangeOpenRequest)(nil),         // 27: securities.IsExchangeOpenRequest
	(*IsExchangeOpenResponse)(nil),        // 28: securities.IsExchangeOpenResponse
	(*GetTestModeRequest)(nil),            // 29: securities.GetTestModeRequest
	(*GetTestModeResponse)(nil),           // 30: securities.GetTestModeResponse
	(*SetTestModeRequest)(nil),            // 31: securities.SetTestModeRequest
	(*SetTestModeResponse)(nil),           // 32: securities.SetTestModeResponse
}
var file_securities_proto_depIdxs = []int32{
	2,  // 0: securities.GetStockExchangesResponse.exchanges:type_name -> securities.StockExchange
	2,  // 1: securities.GetStockExchangeByMICResponse.exchange:type_name -> securities.StockExchange
	2,  // 2: securities.GetStockExchangeByIdResponse.exchange:type_name -> securities.StockExchange
	2,  // 3: securities.CreateStockExchangeResponse.exchange:type_name -> securities.StockExchange
	2,  // 4: securities.UpdateStockExchangeResponse.exchange:type_name -> securities.StockExchange
	15, // 5: securities.GetWorkingHoursResponse.hours:type_name -> securities.ExchangeWorkingHours
	15, // 6: securities.SetWorkingHoursResponse.hours:type_name -> securities.ExchangeWorkingHours
	20, // 7: securities.GetHolidaysResponse.holidays:type_name -> securities.ExchangeHoliday
	20, // 8: securities.AddHolidayResponse.holiday:type_name -> securities.ExchangeHoliday
	0,  // 9: securities.SecuritiesService.Ping:input_type -> securities.PingRequest
	3,  // 10: securities.SecuritiesService.GetStockExchanges:input_type -> securities.GetStockExchangesRequest
	5,  // 11: securities.SecuritiesService.GetStockExchangeByMIC:input_type -> securities.GetStockExchangeByMICRequest
	7,  // 12: securities.SecuritiesService.GetStockExchangeById:input_type -> securities.GetStockExchangeByIdRequest
	9,  // 13: securities.SecuritiesService.CreateStockExchange:input_type -> securities.CreateStockExchangeRequest
	11, // 14: securities.SecuritiesService.UpdateStockExchange:input_type -> securities.UpdateStockExchangeRequest
	13, // 15: securities.SecuritiesService.DeleteStockExchange:input_type -> securities.DeleteStockExchangeRequest
	16, // 16: securities.SecuritiesService.GetWorkingHours:input_type -> securities.GetWorkingHoursRequest
	18, // 17: securities.SecuritiesService.SetWorkingHours:input_type -> securities.SetWorkingHoursRequest
	21, // 18: securities.SecuritiesService.GetHolidays:input_type -> securities.GetHolidaysRequest
	23, // 19: securities.SecuritiesService.AddHoliday:input_type -> securities.AddHolidayRequest
	25, // 20: securities.SecuritiesService.DeleteHoliday:input_type -> securities.DeleteHolidayRequest
	27, // 21: securities.SecuritiesService.IsExchangeOpen:input_type -> securities.IsExchangeOpenRequest
	29, // 22: securities.SecuritiesService.GetTestMode:input_type -> securities.GetTestModeRequest
	31, // 23: securities.SecuritiesService.SetTestMode:input_type -> securities.SetTestModeRequest
	1,  // 24: securities.SecuritiesService.Ping:output_type -> securities.PingResponse
	4,  // 25: securities.SecuritiesService.GetStockExchanges:output_type -> securities.GetStockExchangesResponse
	6,  // 26: securities.SecuritiesService.GetStockExchangeByMIC:output_type -> securities.GetStockExchangeByMICResponse
	8,  // 27: securities.SecuritiesService.GetStockExchangeById:output_type -> securities.GetStockExchangeByIdResponse
	10, // 28: securities.SecuritiesService.CreateStockExchange:output_type -> securities.CreateStockExchangeResponse
	12, // 29: securities.SecuritiesService.UpdateStockExchange:output_type -> securities.UpdateStockExchangeResponse
	14, // 30: securities.SecuritiesService.DeleteStockExchange:output_type -> securities.DeleteStockExchangeResponse
	17, // 31: securities.SecuritiesService.GetWorkingHours:output_type -> securities.GetWorkingHoursResponse
	19, // 32: securities.SecuritiesService.SetWorkingHours:output_type -> securities.SetWorkingHoursResponse
	22, // 33: securities.SecuritiesService.GetHolidays:output_type -> securities.GetHolidaysResponse
	24, // 34: securities.SecuritiesService.AddHoliday:output_type -> securities.AddHolidayResponse
	26, // 35: securities.SecuritiesService.DeleteHoliday:output_type -> securities.DeleteHolidayResponse
	28, // 36: securities.SecuritiesService.IsExchangeOpen:output_type -> securities.IsExchangeOpenResponse
	30, // 37: securities.SecuritiesService.GetTestMode:output_type -> securities.GetTestModeResponse
	32, // 38: securities.SecuritiesService.SetTestMode:output_type -> securities.SetTestModeResponse
	24, // [24:39] is the sub-list for method output_type
	9,  // [9:24] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_securities_proto_init() }
func file_securities_proto_init() {
	if File_securities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_securities_proto_rawDesc), len(file_securities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_securities_proto_goTypes,
		DependencyIndexes: file_securities_proto_depIdxs,
		MessageInfos:      file_securities_proto_msgTypes,
	}.Build()
	File_securities_proto = out.File
	file_securities_proto_goTypes = nil
	file_securities_proto_depIdxs = nil
}
