// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: securities.proto

package securities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_securities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_securities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StockExchange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Acronym       string                 `protobuf:"bytes,3,opt,name=acronym,proto3" json:"acronym,omitempty"`
	MicCode       string                 `protobuf:"bytes,4,opt,name=mic_code,json=micCode,proto3" json:"mic_code,omitempty"`
	Polity        string                 `protobuf:"bytes,5,opt,name=polity,proto3" json:"polity,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Timezone      string                 `protobuf:"bytes,7,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockExchange) Reset() {
	*x = StockExchange{}
	mi := &file_securities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockExchange) ProtoMessage() {}

func (x *StockExchange) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockExchange.ProtoReflect.Descriptor instead.
func (*StockExchange) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{2}
}

func (x *StockExchange) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StockExchange) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StockExchange) GetAcronym() string {
	if x != nil {
		return x.Acronym
	}
	return ""
}

func (x *StockExchange) GetMicCode() string {
	if x != nil {
		return x.MicCode
	}
	return ""
}

func (x *StockExchange) GetPolity() string {
	if x != nil {
		return x.Polity
	}
	return ""
}

func (x *StockExchange) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *StockExchange) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type GetStockExchangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 1-based, default 1
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // default 10
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockExchangesRequest) Reset() {
	*x = GetStockExchangesRequest{}
	mi := &file_securities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockExchangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockExchangesRequest) ProtoMessage() {}

func (x *GetStockExchangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockExchangesRequest.ProtoReflect.Descriptor instead.
func (*GetStockExchangesRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{3}
}

func (x *GetStockExchangesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetStockExchangesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetStockExchangesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchanges     []*StockExchange       `protobuf:"bytes,1,rep,name=exchanges,proto3" json:"exchanges,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockExchangesResponse) Reset() {
	*x = GetStockExchangesResponse{}
	mi := &file_securities_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockExchangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockExchangesResponse) ProtoMessage() {}

func (x *GetStockExchangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockExchangesResponse.ProtoReflect.Descriptor instead.
func (*GetStockExchangesResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{4}
}

func (x *GetStockExchangesResponse) GetExchanges() []*StockExchange {
	if x != nil {
		return x.Exchanges
	}
	return nil
}

func (x *GetStockExchangesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetStockExchangeByMICRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MicCode       string                 `protobuf:"bytes,1,opt,name=mic_code,json=micCode,proto3" json:"mic_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockExchangeByMICRequest) Reset() {
	*x = GetStockExchangeByMICRequest{}
	mi := &file_securities_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockExchangeByMICRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockExchangeByMICRequest) ProtoMessage() {}

func (x *GetStockExchangeByMICRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockExchangeByMICRequest.ProtoReflect.Descriptor instead.
func (*GetStockExchangeByMICRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{5}
}

func (x *GetStockExchangeByMICRequest) GetMicCode() string {
	if x != nil {
		return x.MicCode
	}
	return ""
}

type GetStockExchangeByMICResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      *StockExchange         `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockExchangeByMICResponse) Reset() {
	*x = GetStockExchangeByMICResponse{}
	mi := &file_securities_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockExchangeByMICResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockExchangeByMICResponse) ProtoMessage() {}

func (x *GetStockExchangeByMICResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockExchangeByMICResponse.ProtoReflect.Descriptor instead.
func (*GetStockExchangeByMICResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{6}
}

func (x *GetStockExchangeByMICResponse) GetExchange() *StockExchange {
	if x != nil {
		return x.Exchange
	}
	return nil
}

type GetStockExchangeByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockExchangeByIdRequest) Reset() {
	*x = GetStockExchangeByIdRequest{}
	mi := &file_securities_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockExchangeByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockExchangeByIdRequest) ProtoMessage() {}

func (x *GetStockExchangeByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockExchangeByIdRequest.ProtoReflect.Descriptor instead.
func (*GetStockExchangeByIdRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{7}
}

func (x *GetStockExchangeByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetStockExchangeByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      *StockExchange         `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockExchangeByIdResponse) Reset() {
	*x = GetStockExchangeByIdResponse{}
	mi := &file_securities_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockExchangeByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockExchangeByIdResponse) ProtoMessage() {}

func (x *GetStockExchangeByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockExchangeByIdResponse.ProtoReflect.Descriptor instead.
func (*GetStockExchangeByIdResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{8}
}

func (x *GetStockExchangeByIdResponse) GetExchange() *StockExchange {
	if x != nil {
		return x.Exchange
	}
	return nil
}

type CreateStockExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Acronym       string                 `protobuf:"bytes,2,opt,name=acronym,proto3" json:"acronym,omitempty"`
	MicCode       string                 `protobuf:"bytes,3,opt,name=mic_code,json=micCode,proto3" json:"mic_code,omitempty"`
	Polity        string                 `protobuf:"bytes,4,opt,name=polity,proto3" json:"polity,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Timezone      string                 `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStockExchangeRequest) Reset() {
	*x = CreateStockExchangeRequest{}
	mi := &file_securities_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStockExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStockExchangeRequest) ProtoMessage() {}

func (x *CreateStockExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStockExchangeRequest.ProtoReflect.Descriptor instead.
func (*CreateStockExchangeRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{9}
}

func (x *CreateStockExchangeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateStockExchangeRequest) GetAcronym() string {
	if x != nil {
		return x.Acronym
	}
	return ""
}

func (x *CreateStockExchangeRequest) GetMicCode() string {
	if x != nil {
		return x.MicCode
	}
	return ""
}

func (x *CreateStockExchangeRequest) GetPolity() string {
	if x != nil {
		return x.Polity
	}
	return ""
}

func (x *CreateStockExchangeRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateStockExchangeRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type CreateStockExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      *StockExchange         `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStockExchangeResponse) Reset() {
	*x = CreateStockExchangeResponse{}
	mi := &file_securities_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStockExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStockExchangeResponse) ProtoMessage() {}

func (x *CreateStockExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStockExchangeResponse.ProtoReflect.Descriptor instead.
func (*CreateStockExchangeResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{10}
}

func (x *CreateStockExchangeResponse) GetExchange() *StockExchange {
	if x != nil {
		return x.Exchange
	}
	return nil
}

type UpdateStockExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MicCode       string                 `protobuf:"bytes,1,opt,name=mic_code,json=micCode,proto3" json:"mic_code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Acronym       string                 `protobuf:"bytes,3,opt,name=acronym,proto3" json:"acronym,omitempty"`
	Polity        string                 `protobuf:"bytes,4,opt,name=polity,proto3" json:"polity,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Timezone      string                 `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockExchangeRequest) Reset() {
	*x = UpdateStockExchangeRequest{}
	mi := &file_securities_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockExchangeRequest) ProtoMessage() {}

func (x *UpdateStockExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockExchangeRequest.ProtoReflect.Descriptor instead.
func (*UpdateStockExchangeRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateStockExchangeRequest) GetMicCode() string {
	if x != nil {
		return x.MicCode
	}
	return ""
}

func (x *UpdateStockExchangeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateStockExchangeRequest) GetAcronym() string {
	if x != nil {
		return x.Acronym
	}
	return ""
}

func (x *UpdateStockExchangeRequest) GetPolity() string {
	if x != nil {
		return x.Polity
	}
	return ""
}

func (x *UpdateStockExchangeRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateStockExchangeRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type UpdateStockExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      *StockExchange         `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockExchangeResponse) Reset() {
	*x = UpdateStockExchangeResponse{}
	mi := &file_securities_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockExchangeResponse) ProtoMessage() {}

func (x *UpdateStockExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockExchangeResponse.ProtoReflect.Descriptor instead.
func (*UpdateStockExchangeResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateStockExchangeResponse) GetExchange() *StockExchange {
	if x != nil {
		return x.Exchange
	}
	return nil
}

type DeleteStockExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MicCode       string                 `protobuf:"bytes,1,opt,name=mic_code,json=micCode,proto3" json:"mic_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStockExchangeRequest) Reset() {
	*x = DeleteStockExchangeRequest{}
	mi := &file_securities_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStockExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStockExchangeRequest) ProtoMessage() {}

func (x *DeleteStockExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStockExchangeRequest.ProtoReflect.Descriptor instead.
func (*DeleteStockExchangeRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteStockExchangeRequest) GetMicCode() string {
	if x != nil {
		return x.MicCode
	}
	return ""
}

type DeleteStockExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStockExchangeResponse) Reset() {
	*x = DeleteStockExchangeResponse{}
	mi := &file_securities_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStockExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStockExchangeResponse) ProtoMessage() {}

func (x *DeleteStockExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStockExchangeResponse.ProtoReflect.Descriptor instead.
func (*DeleteStockExchangeResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{14}
}

type ExchangeWorkingHours struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Polity        string                 `protobuf:"bytes,2,opt,name=polity,proto3" json:"polity,omitempty"`
	Segment       string                 `protobuf:"bytes,3,opt,name=segment,proto3" json:"segment,omitempty"`
	OpenTime      string                 `protobuf:"bytes,4,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	CloseTime     string                 `protobuf:"bytes,5,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeWorkingHours) Reset() {
	*x = ExchangeWorkingHours{}
	mi := &file_securities_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeWorkingHours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeWorkingHours) ProtoMessage() {}

func (x *ExchangeWorkingHours) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeWorkingHours.ProtoReflect.Descriptor instead.
func (*ExchangeWorkingHours) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{15}
}

func (x *ExchangeWorkingHours) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExchangeWorkingHours) GetPolity() string {
	if x != nil {
		return x.Polity
	}
	return ""
}

func (x *ExchangeWorkingHours) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

func (x *ExchangeWorkingHours) GetOpenTime() string {
	if x != nil {
		return x.OpenTime
	}
	return ""
}

func (x *ExchangeWorkingHours) GetCloseTime() string {
	if x != nil {
		return x.CloseTime
	}
	return ""
}

type GetWorkingHoursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MicCode       string                 `protobuf:"bytes,1,opt,name=mic_code,json=micCode,proto3" json:"mic_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkingHoursRequest) Reset() {
	*x = GetWorkingHoursRequest{}
	mi := &file_securities_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkingHoursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkingHoursRequest) ProtoMessage() {}

func (x *GetWorkingHoursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkingHoursRequest.ProtoReflect.Descriptor instead.
func (*GetWorkingHoursRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{16}
}

func (x *GetWorkingHoursRequest) GetMicCode() string {
	if x != nil {
		return x.MicCode
	}
	return ""
}

type GetWorkingHoursResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Hours         []*ExchangeWorkingHours `protobuf:"bytes,1,rep,name=hours,proto3" json:"hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkingHoursResponse) Reset() {
	*x = GetWorkingHoursResponse{}
	mi := &file_securities_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkingHoursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkingHoursResponse) ProtoMessage() {}

func (x *GetWorkingHoursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkingHoursResponse.ProtoReflect.Descriptor instead.
func (*GetWorkingHoursResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{17}
}

func (x *GetWorkingHoursResponse) GetHours() []*ExchangeWorkingHours {
	if x != nil {
		return x.Hours
	}
	return nil
}

type SetWorkingHoursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Polity        string                 `protobuf:"bytes,1,opt,name=polity,proto3" json:"polity,omitempty"`
	Segment       string                 `protobuf:"bytes,2,opt,name=segment,proto3" json:"segment,omitempty"`
	OpenTime      string                 `protobuf:"bytes,3,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	CloseTime     string                 `protobuf:"bytes,4,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWorkingHoursRequest) Reset() {
	*x = SetWorkingHoursRequest{}
	mi := &file_securities_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWorkingHoursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWorkingHoursRequest) ProtoMessage() {}

func (x *SetWorkingHoursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWorkingHoursRequest.ProtoReflect.Descriptor instead.
func (*SetWorkingHoursRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{18}
}

func (x *SetWorkingHoursRequest) GetPolity() string {
	if x != nil {
		return x.Polity
	}
	return ""
}

func (x *SetWorkingHoursRequest) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

func (x *SetWorkingHoursRequest) GetOpenTime() string {
	if x != nil {
		return x.OpenTime
	}
	return ""
}

func (x *SetWorkingHoursRequest) GetCloseTime() string {
	if x != nil {
		return x.CloseTime
	}
	return ""
}

type SetWorkingHoursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hours         *ExchangeWorkingHours  `protobuf:"bytes,1,opt,name=hours,proto3" json:"hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetWorkingHoursResponse) Reset() {
	*x = SetWorkingHoursResponse{}
	mi := &file_securities_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetWorkingHoursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetWorkingHoursResponse) ProtoMessage() {}

func (x *SetWorkingHoursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetWorkingHoursResponse.ProtoReflect.Descriptor instead.
func (*SetWorkingHoursResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{19}
}

func (x *SetWorkingHoursResponse) GetHours() *ExchangeWorkingHours {
	if x != nil {
		return x.Hours
	}
	return nil
}

type ExchangeHoliday struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Polity        string                 `protobuf:"bytes,2,opt,name=polity,proto3" json:"polity,omitempty"`
	HolidayDate   string                 `protobuf:"bytes,3,opt,name=holiday_date,json=holidayDate,proto3" json:"holiday_date,omitempty"` // "YYYY-MM-DD"
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeHoliday) Reset() {
	*x = ExchangeHoliday{}
	mi := &file_securities_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeHoliday) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeHoliday) ProtoMessage() {}

func (x *ExchangeHoliday) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeHoliday.ProtoReflect.Descriptor instead.
func (*ExchangeHoliday) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{20}
}

func (x *ExchangeHoliday) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExchangeHoliday) GetPolity() string {
	if x != nil {
		return x.Polity
	}
	return ""
}

func (x *ExchangeHoliday) GetHolidayDate() string {
	if x != nil {
		return x.HolidayDate
	}
	return ""
}

func (x *ExchangeHoliday) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetHolidaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Polity        string                 `protobuf:"bytes,1,opt,name=polity,proto3" json:"polity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHolidaysRequest) Reset() {
	*x = GetHolidaysRequest{}
	mi := &file_securities_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHolidaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHolidaysRequest) ProtoMessage() {}

func (x *GetHolidaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHolidaysRequest.ProtoReflect.Descriptor instead.
func (*GetHolidaysRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{21}
}

func (x *GetHolidaysRequest) GetPolity() string {
	if x != nil {
		return x.Polity
	}
	return ""
}

type GetHolidaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holidays      []*ExchangeHoliday     `protobuf:"bytes,1,rep,name=holidays,proto3" json:"holidays,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHolidaysResponse) Reset() {
	*x = GetHolidaysResponse{}
	mi := &file_securities_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHolidaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHolidaysResponse) ProtoMessage() {}

func (x *GetHolidaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHolidaysResponse.ProtoReflect.Descriptor instead.
func (*GetHolidaysResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{22}
}

func (x *GetHolidaysResponse) GetHolidays() []*ExchangeHoliday {
	if x != nil {
		return x.Holidays
	}
	return nil
}

type AddHolidayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Polity        string                 `protobuf:"bytes,1,opt,name=polity,proto3" json:"polity,omitempty"`
	HolidayDate   string                 `protobuf:"bytes,2,opt,name=holiday_date,json=holidayDate,proto3" json:"holiday_date,omitempty"` // "YYYY-MM-DD"
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddHolidayRequest) Reset() {
	*x = AddHolidayRequest{}
	mi := &file_securities_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddHolidayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHolidayRequest) ProtoMessage() {}

func (x *AddHolidayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHolidayRequest.ProtoReflect.Descriptor instead.
func (*AddHolidayRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{23}
}

func (x *AddHolidayRequest) GetPolity() string {
	if x != nil {
		return x.Polity
	}
	return ""
}

func (x *AddHolidayRequest) GetHolidayDate() string {
	if x != nil {
		return x.HolidayDate
	}
	return ""
}

func (x *AddHolidayRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AddHolidayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holiday       *ExchangeHoliday       `protobuf:"bytes,1,opt,name=holiday,proto3" json:"holiday,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddHolidayResponse) Reset() {
	*x = AddHolidayResponse{}
	mi := &file_securities_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddHolidayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHolidayResponse) ProtoMessage() {}

func (x *AddHolidayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHolidayResponse.ProtoReflect.Descriptor instead.
func (*AddHolidayResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{24}
}

func (x *AddHolidayResponse) GetHoliday() *ExchangeHoliday {
	if x != nil {
		return x.Holiday
	}
	return nil
}

type DeleteHolidayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Polity        string                 `protobuf:"bytes,1,opt,name=polity,proto3" json:"polity,omitempty"`
	HolidayDate   string                 `protobuf:"bytes,2,opt,name=holiday_date,json=holidayDate,proto3" json:"holiday_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHolidayRequest) Reset() {
	*x = DeleteHolidayRequest{}
	mi := &file_securities_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHolidayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHolidayRequest) ProtoMessage() {}

func (x *DeleteHolidayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHolidayRequest.ProtoReflect.Descriptor instead.
func (*DeleteHolidayRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteHolidayRequest) GetPolity() string {
	if x != nil {
		return x.Polity
	}
	return ""
}

func (x *DeleteHolidayRequest) GetHolidayDate() string {
	if x != nil {
		return x.HolidayDate
	}
	return ""
}

type DeleteHolidayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHolidayResponse) Reset() {
	*x = DeleteHolidayResponse{}
	mi := &file_securities_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHolidayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHolidayResponse) ProtoMessage() {}

func (x *DeleteHolidayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHolidayResponse.ProtoReflect.Descriptor instead.
func (*DeleteHolidayResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{26}
}

type IsExchangeOpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MicCode       string                 `protobuf:"bytes,1,opt,name=mic_code,json=micCode,proto3" json:"mic_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsExchangeOpenRequest) Reset() {
	*x = IsExchangeOpenRequest{}
	mi := &file_securities_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsExchangeOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsExchangeOpenRequest) ProtoMessage() {}

func (x *IsExchangeOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsExchangeOpenRequest.ProtoReflect.Descriptor instead.
func (*IsExchangeOpenRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{27}
}

func (x *IsExchangeOpenRequest) GetMicCode() string {
	if x != nil {
		return x.MicCode
	}
	return ""
}

type IsExchangeOpenResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MicCode          string                 `protobuf:"bytes,1,opt,name=mic_code,json=micCode,proto3" json:"mic_code,omitempty"`
	IsOpen           bool                   `protobuf:"varint,2,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	Segment          string                 `protobuf:"bytes,3,opt,name=segment,proto3" json:"segment,omitempty"`                                             // "pre_market", "regular", "post_market", "test_mode", or "closed"
	CurrentTimeLocal string                 `protobuf:"bytes,4,opt,name=current_time_local,json=currentTimeLocal,proto3" json:"current_time_local,omitempty"` // "HH:MM" in exchange's local timezone
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IsExchangeOpenResponse) Reset() {
	*x = IsExchangeOpenResponse{}
	mi := &file_securities_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsExchangeOpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsExchangeOpenResponse) ProtoMessage() {}

func (x *IsExchangeOpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsExchangeOpenResponse.ProtoReflect.Descriptor instead.
func (*IsExchangeOpenResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{28}
}

func (x *IsExchangeOpenResponse) GetMicCode() string {
	if x != nil {
		return x.MicCode
	}
	return ""
}

func (x *IsExchangeOpenResponse) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

func (x *IsExchangeOpenResponse) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

func (x *IsExchangeOpenResponse) GetCurrentTimeLocal() string {
	if x != nil {
		return x.CurrentTimeLocal
	}
	return ""
}

type GetTestModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTestModeRequest) Reset() {
	*x = GetTestModeRequest{}
	mi := &file_securities_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTestModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestModeRequest) ProtoMessage() {}

func (x *GetTestModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestModeRequest.ProtoReflect.Descriptor instead.
func (*GetTestModeRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{29}
}

type GetTestModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTestModeResponse) Reset() {
	*x = GetTestModeResponse{}
	mi := &file_securities_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTestModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTestModeResponse) ProtoMessage() {}

func (x *GetTestModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTestModeResponse.ProtoReflect.Descriptor instead.
func (*GetTestModeResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{30}
}

func (x *GetTestModeResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SetTestModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTestModeRequest) Reset() {
	*x = SetTestModeRequest{}
	mi := &file_securities_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTestModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTestModeRequest) ProtoMessage() {}

func (x *SetTestModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTestModeRequest.ProtoReflect.Descriptor instead.
func (*SetTestModeRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{31}
}

func (x *SetTestModeRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SetTestModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTestModeResponse) Reset() {
	*x = SetTestModeResponse{}
	mi := &file_securities_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTestModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTestModeResponse) ProtoMessage() {}

func (x *SetTestModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTestModeResponse.ProtoReflect.Descriptor instead.
func (*SetTestModeResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{32}
}

func (x *SetTestModeResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type GetListingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                // STOCK, FOREX_PAIR, FUTURES_CONTRACT, OPTION — empty = all
	ExchangeId    int64                  `protobuf:"varint,2,opt,name=exchange_id,json=exchangeId,proto3" json:"exchange_id,omitempty"` // 0 = all exchanges
	TickerPrefix  string                 `protobuf:"bytes,3,opt,name=ticker_prefix,json=tickerPrefix,proto3" json:"ticker_prefix,omitempty"`
	NameSearch    string                 `protobuf:"bytes,4,opt,name=name_search,json=nameSearch,proto3" json:"name_search,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`                           // 1-based, default 1
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // default 10
	SortBy        string                 `protobuf:"bytes,7,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`          // price, volume, change_percent, maintenance_margin
	SortOrder     string                 `protobuf:"bytes,8,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // ASC, DESC
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingsRequest) Reset() {
	*x = GetListingsRequest{}
	mi := &file_securities_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingsRequest) ProtoMessage() {}

func (x *GetListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingsRequest.ProtoReflect.Descriptor instead.
func (*GetListingsRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{33}
}

func (x *GetListingsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetListingsRequest) GetExchangeId() int64 {
	if x != nil {
		return x.ExchangeId
	}
	return 0
}

func (x *GetListingsRequest) GetTickerPrefix() string {
	if x != nil {
		return x.TickerPrefix
	}
	return ""
}

func (x *GetListingsRequest) GetNameSearch() string {
	if x != nil {
		return x.NameSearch
	}
	return ""
}

func (x *GetListingsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetListingsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *GetListingsRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type ListingSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ticker            string                 `protobuf:"bytes,2,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type              string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	ExchangeAcronym   string                 `protobuf:"bytes,5,opt,name=exchange_acronym,json=exchangeAcronym,proto3" json:"exchange_acronym,omitempty"`
	Price             float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Ask               float64                `protobuf:"fixed64,7,opt,name=ask,proto3" json:"ask,omitempty"`
	Bid               float64                `protobuf:"fixed64,8,opt,name=bid,proto3" json:"bid,omitempty"`
	Volume            int64                  `protobuf:"varint,9,opt,name=volume,proto3" json:"volume,omitempty"`
	ChangePercent     float64                `protobuf:"fixed64,10,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`
	MaintenanceMargin float64                `protobuf:"fixed64,11,opt,name=maintenance_margin,json=maintenanceMargin,proto3" json:"maintenance_margin,omitempty"`
	InitialMarginCost float64                `protobuf:"fixed64,12,opt,name=initial_margin_cost,json=initialMarginCost,proto3" json:"initial_margin_cost,omitempty"`
	NominalValue      float64                `protobuf:"fixed64,13,opt,name=nominal_value,json=nominalValue,proto3" json:"nominal_value,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListingSummary) Reset() {
	*x = ListingSummary{}
	mi := &file_securities_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListingSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListingSummary) ProtoMessage() {}

func (x *ListingSummary) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListingSummary.ProtoReflect.Descriptor instead.
func (*ListingSummary) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{34}
}

func (x *ListingSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListingSummary) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *ListingSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListingSummary) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListingSummary) GetExchangeAcronym() string {
	if x != nil {
		return x.ExchangeAcronym
	}
	return ""
}

func (x *ListingSummary) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ListingSummary) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *ListingSummary) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *ListingSummary) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *ListingSummary) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

func (x *ListingSummary) GetMaintenanceMargin() float64 {
	if x != nil {
		return x.MaintenanceMargin
	}
	return 0
}

func (x *ListingSummary) GetInitialMarginCost() float64 {
	if x != nil {
		return x.InitialMarginCost
	}
	return 0
}

func (x *ListingSummary) GetNominalValue() float64 {
	if x != nil {
		return x.NominalValue
	}
	return 0
}

type GetListingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listings      []*ListingSummary      `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	TotalPages    int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalElements int64                  `protobuf:"varint,3,opt,name=total_elements,json=totalElements,proto3" json:"total_elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingsResponse) Reset() {
	*x = GetListingsResponse{}
	mi := &file_securities_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingsResponse) ProtoMessage() {}

func (x *GetListingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingsResponse.ProtoReflect.Descriptor instead.
func (*GetListingsResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{35}
}

func (x *GetListingsResponse) GetListings() []*ListingSummary {
	if x != nil {
		return x.Listings
	}
	return nil
}

func (x *GetListingsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetListingsResponse) GetTotalElements() int64 {
	if x != nil {
		return x.TotalElements
	}
	return 0
}

type GetListingByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingByIdRequest) Reset() {
	*x = GetListingByIdRequest{}
	mi := &file_securities_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingByIdRequest) ProtoMessage() {}

func (x *GetListingByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingByIdRequest.ProtoReflect.Descriptor instead.
func (*GetListingByIdRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{36}
}

func (x *GetListingByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DailyPriceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // "YYYY-MM-DD"
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Ask           float64                `protobuf:"fixed64,3,opt,name=ask,proto3" json:"ask,omitempty"`
	Bid           float64                `protobuf:"fixed64,4,opt,name=bid,proto3" json:"bid,omitempty"`
	Change        float64                `protobuf:"fixed64,5,opt,name=change,proto3" json:"change,omitempty"`
	Volume        int64                  `protobuf:"varint,6,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyPriceInfo) Reset() {
	*x = DailyPriceInfo{}
	mi := &file_securities_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyPriceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyPriceInfo) ProtoMessage() {}

func (x *DailyPriceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyPriceInfo.ProtoReflect.Descriptor instead.
func (*DailyPriceInfo) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{37}
}

func (x *DailyPriceInfo) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyPriceInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *DailyPriceInfo) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *DailyPriceInfo) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *DailyPriceInfo) GetChange() float64 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *DailyPriceInfo) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type StockDetail struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OutstandingShares int64                  `protobuf:"varint,1,opt,name=outstanding_shares,json=outstandingShares,proto3" json:"outstanding_shares,omitempty"`
	DividendYield     float64                `protobuf:"fixed64,2,opt,name=dividend_yield,json=dividendYield,proto3" json:"dividend_yield,omitempty"`
	MarketCap         float64                `protobuf:"fixed64,3,opt,name=market_cap,json=marketCap,proto3" json:"market_cap,omitempty"` // derived: outstanding_shares × price
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StockDetail) Reset() {
	*x = StockDetail{}
	mi := &file_securities_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockDetail) ProtoMessage() {}

func (x *StockDetail) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockDetail.ProtoReflect.Descriptor instead.
func (*StockDetail) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{38}
}

func (x *StockDetail) GetOutstandingShares() int64 {
	if x != nil {
		return x.OutstandingShares
	}
	return 0
}

func (x *StockDetail) GetDividendYield() float64 {
	if x != nil {
		return x.DividendYield
	}
	return 0
}

func (x *StockDetail) GetMarketCap() float64 {
	if x != nil {
		return x.MarketCap
	}
	return 0
}

type ForexDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseCurrency  string                 `protobuf:"bytes,1,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	QuoteCurrency string                 `protobuf:"bytes,2,opt,name=quote_currency,json=quoteCurrency,proto3" json:"quote_currency,omitempty"`
	Liquidity     string                 `protobuf:"bytes,3,opt,name=liquidity,proto3" json:"liquidity,omitempty"`
	NominalValue  float64                `protobuf:"fixed64,4,opt,name=nominal_value,json=nominalValue,proto3" json:"nominal_value,omitempty"` // derived: 1000 × price
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForexDetail) Reset() {
	*x = ForexDetail{}
	mi := &file_securities_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForexDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForexDetail) ProtoMessage() {}

func (x *ForexDetail) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForexDetail.ProtoReflect.Descriptor instead.
func (*ForexDetail) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{39}
}

func (x *ForexDetail) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *ForexDetail) GetQuoteCurrency() string {
	if x != nil {
		return x.QuoteCurrency
	}
	return ""
}

func (x *ForexDetail) GetLiquidity() string {
	if x != nil {
		return x.Liquidity
	}
	return ""
}

func (x *ForexDetail) GetNominalValue() float64 {
	if x != nil {
		return x.NominalValue
	}
	return 0
}

type FuturesDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContractSize   float64                `protobuf:"fixed64,1,opt,name=contract_size,json=contractSize,proto3" json:"contract_size,omitempty"`
	ContractUnit   string                 `protobuf:"bytes,2,opt,name=contract_unit,json=contractUnit,proto3" json:"contract_unit,omitempty"`
	SettlementDate string                 `protobuf:"bytes,3,opt,name=settlement_date,json=settlementDate,proto3" json:"settlement_date,omitempty"` // "YYYY-MM-DD"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FuturesDetail) Reset() {
	*x = FuturesDetail{}
	mi := &file_securities_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuturesDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuturesDetail) ProtoMessage() {}

func (x *FuturesDetail) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuturesDetail.ProtoReflect.Descriptor instead.
func (*FuturesDetail) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{40}
}

func (x *FuturesDetail) GetContractSize() float64 {
	if x != nil {
		return x.ContractSize
	}
	return 0
}

func (x *FuturesDetail) GetContractUnit() string {
	if x != nil {
		return x.ContractUnit
	}
	return ""
}

func (x *FuturesDetail) GetSettlementDate() string {
	if x != nil {
		return x.SettlementDate
	}
	return ""
}

type OptionDetail struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StockListingId    int64                  `protobuf:"varint,1,opt,name=stock_listing_id,json=stockListingId,proto3" json:"stock_listing_id,omitempty"`
	OptionType        string                 `protobuf:"bytes,2,opt,name=option_type,json=optionType,proto3" json:"option_type,omitempty"` // CALL, PUT
	StrikePrice       float64                `protobuf:"fixed64,3,opt,name=strike_price,json=strikePrice,proto3" json:"strike_price,omitempty"`
	ImpliedVolatility float64                `protobuf:"fixed64,4,opt,name=implied_volatility,json=impliedVolatility,proto3" json:"implied_volatility,omitempty"`
	OpenInterest      int64                  `protobuf:"varint,5,opt,name=open_interest,json=openInterest,proto3" json:"open_interest,omitempty"`
	SettlementDate    string                 `protobuf:"bytes,6,opt,name=settlement_date,json=settlementDate,proto3" json:"settlement_date,omitempty"` // "YYYY-MM-DD"
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OptionDetail) Reset() {
	*x = OptionDetail{}
	mi := &file_securities_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionDetail) ProtoMessage() {}

func (x *OptionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionDetail.ProtoReflect.Descriptor instead.
func (*OptionDetail) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{41}
}

func (x *OptionDetail) GetStockListingId() int64 {
	if x != nil {
		return x.StockListingId
	}
	return 0
}

func (x *OptionDetail) GetOptionType() string {
	if x != nil {
		return x.OptionType
	}
	return ""
}

func (x *OptionDetail) GetStrikePrice() float64 {
	if x != nil {
		return x.StrikePrice
	}
	return 0
}

func (x *OptionDetail) GetImpliedVolatility() float64 {
	if x != nil {
		return x.ImpliedVolatility
	}
	return 0
}

func (x *OptionDetail) GetOpenInterest() int64 {
	if x != nil {
		return x.OpenInterest
	}
	return 0
}

func (x *OptionDetail) GetSettlementDate() string {
	if x != nil {
		return x.SettlementDate
	}
	return ""
}

type GetListingByIdResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Summary      *ListingSummary        `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	PriceHistory []*DailyPriceInfo      `protobuf:"bytes,2,rep,name=price_history,json=priceHistory,proto3" json:"price_history,omitempty"` // last 30 days, descending
	// Types that are valid to be assigned to Detail:
	//
	//	*GetListingByIdResponse_Stock
	//	*GetListingByIdResponse_Forex
	//	*GetListingByIdResponse_Futures
	//	*GetListingByIdResponse_Option
	Detail        isGetListingByIdResponse_Detail `protobuf_oneof:"detail"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingByIdResponse) Reset() {
	*x = GetListingByIdResponse{}
	mi := &file_securities_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingByIdResponse) ProtoMessage() {}

func (x *GetListingByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingByIdResponse.ProtoReflect.Descriptor instead.
func (*GetListingByIdResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{42}
}

func (x *GetListingByIdResponse) GetSummary() *ListingSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *GetListingByIdResponse) GetPriceHistory() []*DailyPriceInfo {
	if x != nil {
		return x.PriceHistory
	}
	return nil
}

func (x *GetListingByIdResponse) GetDetail() isGetListingByIdResponse_Detail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *GetListingByIdResponse) GetStock() *StockDetail {
	if x != nil {
		if x, ok := x.Detail.(*GetListingByIdResponse_Stock); ok {
			return x.Stock
		}
	}
	return nil
}

func (x *GetListingByIdResponse) GetForex() *ForexDetail {
	if x != nil {
		if x, ok := x.Detail.(*GetListingByIdResponse_Forex); ok {
			return x.Forex
		}
	}
	return nil
}

func (x *GetListingByIdResponse) GetFutures() *FuturesDetail {
	if x != nil {
		if x, ok := x.Detail.(*GetListingByIdResponse_Futures); ok {
			return x.Futures
		}
	}
	return nil
}

func (x *GetListingByIdResponse) GetOption() *OptionDetail {
	if x != nil {
		if x, ok := x.Detail.(*GetListingByIdResponse_Option); ok {
			return x.Option
		}
	}
	return nil
}

type isGetListingByIdResponse_Detail interface {
	isGetListingByIdResponse_Detail()
}

type GetListingByIdResponse_Stock struct {
	Stock *StockDetail `protobuf:"bytes,3,opt,name=stock,proto3,oneof"`
}

type GetListingByIdResponse_Forex struct {
	Forex *ForexDetail `protobuf:"bytes,4,opt,name=forex,proto3,oneof"`
}

type GetListingByIdResponse_Futures struct {
	Futures *FuturesDetail `protobuf:"bytes,5,opt,name=futures,proto3,oneof"`
}

type GetListingByIdResponse_Option struct {
	Option *OptionDetail `protobuf:"bytes,6,opt,name=option,proto3,oneof"`
}

func (*GetListingByIdResponse_Stock) isGetListingByIdResponse_Detail() {}

func (*GetListingByIdResponse_Forex) isGetListingByIdResponse_Detail() {}

func (*GetListingByIdResponse_Futures) isGetListingByIdResponse_Detail() {}

func (*GetListingByIdResponse_Option) isGetListingByIdResponse_Detail() {}

type GetListingHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromDate      string                 `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"` // "YYYY-MM-DD"
	ToDate        string                 `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`       // "YYYY-MM-DD"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingHistoryRequest) Reset() {
	*x = GetListingHistoryRequest{}
	mi := &file_securities_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingHistoryRequest) ProtoMessage() {}

func (x *GetListingHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetListingHistoryRequest) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{43}
}

func (x *GetListingHistoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetListingHistoryRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *GetListingHistoryRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

type GetListingHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*DailyPriceInfo      `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingHistoryResponse) Reset() {
	*x = GetListingHistoryResponse{}
	mi := &file_securities_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingHistoryResponse) ProtoMessage() {}

func (x *GetListingHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securities_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetListingHistoryResponse) Descriptor() ([]byte, []int) {
	return file_securities_proto_rawDescGZIP(), []int{44}
}

func (x *GetListingHistoryResponse) GetHistory() []*DailyPriceInfo {
	if x != nil {
		return x.History
	}
	return nil
}

var File_securities_proto protoreflect.FileDescriptor

const file_securities_proto_rawDesc = "" +
	"\n" +
	"\x10securities.proto\x12\n" +
	"securities\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xb8\x01\n" +
	"\rStockExchange\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aacronym\x18\x03 \x01(\tR\aacronym\x12\x19\n" +
	"\bmic_code\x18\x04 \x01(\tR\amicCode\x12\x16\n" +
	"\x06polity\x18\x05 \x01(\tR\x06polity\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x1a\n" +
	"\btimezone\x18\a \x01(\tR\btimezone\"K\n" +
	"\x18GetStockExchangesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"u\n" +
	"\x19GetStockExchangesResponse\x127\n" +
	"\texchanges\x18\x01 \x03(\v2\x19.securities.StockExchangeR\texchanges\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"9\n" +
	"\x1cGetStockExchangeByMICRequest\x12\x19\n" +
	"\bmic_code\x18\x01 \x01(\tR\amicCode\"V\n" +
	"\x1dGetStockExchangeByMICResponse\x125\n" +
	"\bexchange\x18\x01 \x01(\v2\x19.securities.StockExchangeR\bexchange\"-\n" +
	"\x1bGetStockExchangeByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"U\n" +
	"\x1cGetStockExchangeByIdResponse\x125\n" +
	"\bexchange\x18\x01 \x01(\v2\x19.securities.StockExchangeR\bexchange\"\xb5\x01\n" +
	"\x1aCreateStockExchangeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aacronym\x18\x02 \x01(\tR\aacronym\x12\x19\n" +
	"\bmic_code\x18\x03 \x01(\tR\amicCode\x12\x16\n" +
	"\x06polity\x18\x04 \x01(\tR\x06polity\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1a\n" +
	"\btimezone\x18\x06 \x01(\tR\btimezone\"T\n" +
	"\x1bCreateStockExchangeResponse\x125\n" +
	"\bexchange\x18\x01 \x01(\v2\x19.securities.StockExchangeR\bexchange\"\xb5\x01\n" +
	"\x1aUpdateStockExchangeRequest\x12\x19\n" +
	"\bmic_code\x18\x01 \x01(\tR\amicCode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aacronym\x18\x03 \x01(\tR\aacronym\x12\x16\n" +
	"\x06polity\x18\x04 \x01(\tR\x06polity\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1a\n" +
	"\btimezone\x18\x06 \x01(\tR\btimezone\"T\n" +
	"\x1bUpdateStockExchangeResponse\x125\n" +
	"\bexchange\x18\x01 \x01(\v2\x19.securities.StockExchangeR\bexchange\"7\n" +
	"\x1aDeleteStockExchangeRequest\x12\x19\n" +
	"\bmic_code\x18\x01 \x01(\tR\amicCode\"\x1d\n" +
	"\x1bDeleteStockExchangeResponse\"\x94\x01\n" +
	"\x14ExchangeWorkingHours\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06polity\x18\x02 \x01(\tR\x06polity\x12\x18\n" +
	"\asegment\x18\x03 \x01(\tR\asegment\x12\x1b\n" +
	"\topen_time\x18\x04 \x01(\tR\bopenTime\x12\x1d\n" +
	"\n" +
	"close_time\x18\x05 \x01(\tR\tcloseTime\"3\n" +
	"\x16GetWorkingHoursRequest\x12\x19\n" +
	"\bmic_code\x18\x01 \x01(\tR\amicCode\"Q\n" +
	"\x17GetWorkingHoursResponse\x126\n" +
	"\x05hours\x18\x01 \x03(\v2 .securities.ExchangeWorkingHoursR\x05hours\"\x86\x01\n" +
	"\x16SetWorkingHoursRequest\x12\x16\n" +
	"\x06polity\x18\x01 \x01(\tR\x06polity\x12\x18\n" +
	"\asegment\x18\x02 \x01(\tR\asegment\x12\x1b\n" +
	"\topen_time\x18\x03 \x01(\tR\bopenTime\x12\x1d\n" +
	"\n" +
	"close_time\x18\x04 \x01(\tR\tcloseTime\"Q\n" +
	"\x17SetWorkingHoursResponse\x126\n" +
	"\x05hours\x18\x01 \x01(\v2 .securities.ExchangeWorkingHoursR\x05hours\"~\n" +
	"\x0fExchangeHoliday\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06polity\x18\x02 \x01(\tR\x06polity\x12!\n" +
	"\fholiday_date\x18\x03 \x01(\tR\vholidayDate\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\",\n" +
	"\x12GetHolidaysRequest\x12\x16\n" +
	"\x06polity\x18\x01 \x01(\tR\x06polity\"N\n" +
	"\x13GetHolidaysResponse\x127\n" +
	"\bholidays\x18\x01 \x03(\v2\x1b.securities.ExchangeHolidayR\bholidays\"p\n" +
	"\x11AddHolidayRequest\x12\x16\n" +
	"\x06polity\x18\x01 \x01(\tR\x06polity\x12!\n" +
	"\fholiday_date\x18\x02 \x01(\tR\vholidayDate\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"K\n" +
	"\x12AddHolidayResponse\x125\n" +
	"\aholiday\x18\x01 \x01(\v2\x1b.securities.ExchangeHolidayR\aholiday\"Q\n" +
	"\x14DeleteHolidayRequest\x12\x16\n" +
	"\x06polity\x18\x01 \x01(\tR\x06polity\x12!\n" +
	"\fholiday_date\x18\x02 \x01(\tR\vholidayDate\"\x17\n" +
	"\x15DeleteHolidayResponse\"2\n" +
	"\x15IsExchangeOpenRequest\x12\x19\n" +
	"\bmic_code\x18\x01 \x01(\tR\amicCode\"\x94\x01\n" +
	"\x16IsExchangeOpenResponse\x12\x19\n" +
	"\bmic_code\x18\x01 \x01(\tR\amicCode\x12\x17\n" +
	"\ais_open\x18\x02 \x01(\bR\x06isOpen\x12\x18\n" +
	"\asegment\x18\x03 \x01(\tR\asegment\x12,\n" +
	"\x12current_time_local\x18\x04 \x01(\tR\x10currentTimeLocal\"\x14\n" +
	"\x12GetTestModeRequest\"/\n" +
	"\x13GetTestModeResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\".\n" +
	"\x12SetTestModeRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"/\n" +
	"\x13SetTestModeResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"\xf8\x01\n" +
	"\x12GetListingsRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1f\n" +
	"\vexchange_id\x18\x02 \x01(\x03R\n" +
	"exchangeId\x12#\n" +
	"\rticker_prefix\x18\x03 \x01(\tR\ftickerPrefix\x12\x1f\n" +
	"\vname_search\x18\x04 \x01(\tR\n" +
	"nameSearch\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\a \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\b \x01(\tR\tsortOrder\"\x88\x03\n" +
	"\x0eListingSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06ticker\x18\x02 \x01(\tR\x06ticker\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12)\n" +
	"\x10exchange_acronym\x18\x05 \x01(\tR\x0fexchangeAcronym\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12\x10\n" +
	"\x03ask\x18\a \x01(\x01R\x03ask\x12\x10\n" +
	"\x03bid\x18\b \x01(\x01R\x03bid\x12\x16\n" +
	"\x06volume\x18\t \x01(\x03R\x06volume\x12%\n" +
	"\x0echange_percent\x18\n" +
	" \x01(\x01R\rchangePercent\x12-\n" +
	"\x12maintenance_margin\x18\v \x01(\x01R\x11maintenanceMargin\x12.\n" +
	"\x13initial_margin_cost\x18\f \x01(\x01R\x11initialMarginCost\x12#\n" +
	"\rnominal_value\x18\r \x01(\x01R\fnominalValue\"\x95\x01\n" +
	"\x13GetListingsResponse\x126\n" +
	"\blistings\x18\x01 \x03(\v2\x1a.securities.ListingSummaryR\blistings\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12%\n" +
	"\x0etotal_elements\x18\x03 \x01(\x03R\rtotalElements\"'\n" +
	"\x15GetListingByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x8e\x01\n" +
	"\x0eDailyPriceInfo\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x10\n" +
	"\x03ask\x18\x03 \x01(\x01R\x03ask\x12\x10\n" +
	"\x03bid\x18\x04 \x01(\x01R\x03bid\x12\x16\n" +
	"\x06change\x18\x05 \x01(\x01R\x06change\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\x03R\x06volume\"\x82\x01\n" +
	"\vStockDetail\x12-\n" +
	"\x12outstanding_shares\x18\x01 \x01(\x03R\x11outstandingShares\x12%\n" +
	"\x0edividend_yield\x18\x02 \x01(\x01R\rdividendYield\x12\x1d\n" +
	"\n" +
	"market_cap\x18\x03 \x01(\x01R\tmarketCap\"\x9c\x01\n" +
	"\vForexDetail\x12#\n" +
	"\rbase_currency\x18\x01 \x01(\tR\fbaseCurrency\x12%\n" +
	"\x0equote_currency\x18\x02 \x01(\tR\rquoteCurrency\x12\x1c\n" +
	"\tliquidity\x18\x03 \x01(\tR\tliquidity\x12#\n" +
	"\rnominal_value\x18\x04 \x01(\x01R\fnominalValue\"\x82\x01\n" +
	"\rFuturesDetail\x12#\n" +
	"\rcontract_size\x18\x01 \x01(\x01R\fcontractSize\x12#\n" +
	"\rcontract_unit\x18\x02 \x01(\tR\fcontractUnit\x12'\n" +
	"\x0fsettlement_date\x18\x03 \x01(\tR\x0esettlementDate\"\xf9\x01\n" +
	"\fOptionDetail\x12(\n" +
	"\x10stock_listing_id\x18\x01 \x01(\x03R\x0estockListingId\x12\x1f\n" +
	"\voption_type\x18\x02 \x01(\tR\n" +
	"optionType\x12!\n" +
	"\fstrike_price\x18\x03 \x01(\x01R\vstrikePrice\x12-\n" +
	"\x12implied_volatility\x18\x04 \x01(\x01R\x11impliedVolatility\x12#\n" +
	"\ropen_interest\x18\x05 \x01(\x03R\fopenInterest\x12'\n" +
	"\x0fsettlement_date\x18\x06 \x01(\tR\x0esettlementDate\"\xe6\x02\n" +
	"\x16GetListingByIdResponse\x124\n" +
	"\asummary\x18\x01 \x01(\v2\x1a.securities.ListingSummaryR\asummary\x12?\n" +
	"\rprice_history\x18\x02 \x03(\v2\x1a.securities.DailyPriceInfoR\fpriceHistory\x12/\n" +
	"\x05stock\x18\x03 \x01(\v2\x17.securities.StockDetailH\x00R\x05stock\x12/\n" +
	"\x05forex\x18\x04 \x01(\v2\x17.securities.ForexDetailH\x00R\x05forex\x125\n" +
	"\afutures\x18\x05 \x01(\v2\x19.securities.FuturesDetailH\x00R\afutures\x122\n" +
	"\x06option\x18\x06 \x01(\v2\x18.securities.OptionDetailH\x00R\x06optionB\b\n" +
	"\x06detail\"`\n" +
	"\x18GetListingHistoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tfrom_date\x18\x02 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\x03 \x01(\tR\x06toDate\"Q\n" +
	"\x19GetListingHistoryResponse\x124\n" +
	"\ahistory\x18\x01 \x03(\v2\x1a.securities.DailyPriceInfoR\ahistory2\xf0\f\n" +
	"\x11SecuritiesService\x129\n" +
	"\x04Ping\x12\x17.securities.PingRequest\x1a\x18.securities.PingResponse\x12`\n" +
	"\x11GetStockExchanges\x12$.securities.GetStockExchangesRequest\x1a%.securities.GetStockExchangesResponse\x12l\n" +
	"\x15GetStockExchangeByMIC\x12(.securities.GetStockExchangeByMICRequest\x1a).securities.GetStockExchangeByMICResponse\x12i\n" +
	"\x14GetStockExchangeById\x12'.securities.GetStockExchangeByIdRequest\x1a(.securities.GetStockExchangeByIdResponse\x12f\n" +
	"\x13CreateStockExchange\x12&.securities.CreateStockExchangeRequest\x1a'.securities.CreateStockExchangeResponse\x12f\n" +
	"\x13UpdateStockExchange\x12&.securities.UpdateStockExchangeRequest\x1a'.securities.UpdateStockExchangeResponse\x12f\n" +
	"\x13DeleteStockExchange\x12&.securities.DeleteStockExchangeRequest\x1a'.securities.DeleteStockExchangeResponse\x12Z\n" +
	"\x0fGetWorkingHours\x12\".securities.GetWorkingHoursRequest\x1a#.securities.GetWorkingHoursResponse\x12Z\n" +
	"\x0fSetWorkingHours\x12\".securities.SetWorkingHoursRequest\x1a#.securities.SetWorkingHoursResponse\x12N\n" +
	"\vGetHolidays\x12\x1e.securities.GetHolidaysRequest\x1a\x1f.securities.GetHolidaysResponse\x12K\n" +
	"\n" +
	"AddHoliday\x12\x1d.securities.AddHolidayRequest\x1a\x1e.securities.AddHolidayResponse\x12T\n" +
	"\rDeleteHoliday\x12 .securities.DeleteHolidayRequest\x1a!.securities.DeleteHolidayResponse\x12W\n" +
	"\x0eIsExchangeOpen\x12!.securities.IsExchangeOpenRequest\x1a\".securities.IsExchangeOpenResponse\x12N\n" +
	"\vGetTestMode\x12\x1e.securities.GetTestModeRequest\x1a\x1f.securities.GetTestModeResponse\x12N\n" +
	"\vSetTestMode\x12\x1e.securities.SetTestModeRequest\x1a\x1f.securities.SetTestModeResponse\x12N\n" +
	"\vGetListings\x12\x1e.securities.GetListingsRequest\x1a\x1f.securities.GetListingsResponse\x12W\n" +
	"\x0eGetListingById\x12!.securities.GetListingByIdRequest\x1a\".securities.GetListingByIdResponse\x12`\n" +
	"\x11GetListingHistory\x12$.securities.GetListingHistoryRequest\x1a%.securities.GetListingHistoryResponseB?Z=github.com/RAF-SI-2025/EXBanka-4-Backend/shared/pb/securitiesb\x06proto3"

var (
	file_securities_proto_rawDescOnce sync.Once
	file_securities_proto_rawDescData []byte
)

func file_securities_proto_rawDescGZIP() []byte {
	file_securities_proto_rawDescOnce.Do(func() {
		file_securities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_securities_proto_rawDesc), len(file_securities_proto_rawDesc)))
	})
	return file_securities_proto_rawDescData
}

var file_securities_proto_msgTypes = make([]protoimpl.MessageInfo, 45)
var file_securities_proto_goTypes = []any{
	(*PingRequest)(nil),                   // 0: securities.PingRequest
	(*PingResponse)(nil),                  // 1: securities.PingResponse
	(*StockExchange)(nil),                 // 2: securities.StockExchange
	(*GetStockExchangesRequest)(nil),      // 3: securities.GetStockExchangesRequest
	(*GetStockExchangesResponse)(nil),     // 4: securities.GetStockExchangesResponse
	(*GetStockExchangeByMICRequest)(nil),  // 5: securities.GetStockExchangeByMICRequest
	(*GetStockExchangeByMICResponse)(nil), // 6: securities.GetStockExchangeByMICResponse
	(*GetStockExchangeByIdRequest)(nil),   // 7: securities.GetStockExchangeByIdRequest
	(*GetStockExchangeByIdResponse)(nil),  // 8: securities.GetStockExchangeByIdResponse
	(*CreateStockExchangeRequest)(nil),    // 9: securities.CreateStockExchangeRequest
	(*CreateStockExchangeResponse)(nil),   // 10: securities.CreateStockExchangeResponse
	(*UpdateStockExchangeRequest)(nil),    // 11: securities.UpdateStockExchangeRequest
	(*UpdateStockExchangeResponse)(nil),   // 12: securities.UpdateStockExchangeResponse
	(*DeleteStockExchangeRequest)(nil),    // 13: securities.DeleteStockExchangeRequest
	(*DeleteStockExchangeResponse)(nil),   // 14: securities.DeleteStockExchangeResponse
	(*ExchangeWorkingHours)(nil),          // 15: securities.ExchangeWorkingHours
	(*GetWorkingHoursRequest)(nil),        // 16: securities.GetWorkingHoursRequest
	(*GetWorkingHoursResponse)(nil),       // 17: securities.GetWorkingHoursResponse
	(*SetWorkingHoursRequest)(nil),        // 18: securities.SetWorkingHoursRequest
	(*SetWorkingHoursResponse)(nil),       // 19: securities.SetWorkingHoursResponse
	(*ExchangeHoliday)(nil),               // 20: securities.ExchangeHoliday
	(*GetHolidaysRequest)(nil),            // 21: securities.GetHolidaysRequest
	(*GetHolidaysResponse)(nil),           // 22: securities.GetHolidaysResponse
	(*AddHolidayRequest)(nil),             // 23: securities.AddHolidayRequest
	(*AddHolidayResponse)(nil),            // 24: securities.AddHolidayResponse
	(*DeleteHolidayRequest)(nil),          // 25: securities.DeleteHolidayRequest
	(*DeleteHolidayResponse)(nil),         // 26: securities.DeleteHolidayResponse
	(*IsExchangeOpenRequest)(nil),         // 27: securities.IsExchangeOpenRequest
	(*IsExchangeOpenResponse)(nil),        // 28: securities.IsExchangeOpenResponse
	(*GetTestModeRequest)(nil),            // 29: securities.GetTestModeRequest
	(*GetTestModeResponse)(nil),           // 30: securities.GetTestModeResponse
	(*SetTestModeRequest)(nil),            // 31: securities.SetTestModeRequest
	(*SetTestModeResponse)(nil),           // 32: securities.SetTestModeResponse
	(*GetListingsRequest)(nil),            // 33: securities.GetListingsRequest
	(*ListingSummary)(nil),                // 34: securities.ListingSummary
	(*GetListingsResponse)(nil),           // 35: securities.GetListingsResponse
	(*GetListingByIdRequest)(nil),         // 36: securities.GetListingByIdRequest
	(*DailyPriceInfo)(nil),                // 37: securities.DailyPriceInfo
	(*StockDetail)(nil),                   // 38: securities.StockDetail
	(*ForexDetail)(nil),                   // 39: securities.ForexDetail
	(*FuturesDetail)(nil),                 // 40: securities.FuturesDetail
	(*OptionDetail)(nil),                  // 41: securities.OptionDetail
	(*GetListingByIdResponse)(nil),        // 42: securities.GetListingByIdResponse
	(*GetListingHistoryRequest)(nil),      // 43: securities.GetListingHistoryRequest
	(*GetListingHistoryResponse)(nil),     // 44: securities.GetListingHistoryResponse
}
var file_securities_proto_depIdxs = []int32{
	2,  // 0: securities.GetStockExchangesResponse.exchanges:type_name -> securities.StockExchange
	2,  // 1: securities.GetStockExchangeByMICResponse.exchange:type_name -> securities.StockExchange
	2,  // 2: securities.GetStockExchangeByIdResponse.exchange:type_name -> securities.StockExchange
	2,  // 3: securities.CreateStockExchangeResponse.exchange:type_name -> securities.StockExchange
	2,  // 4: securities.UpdateStockExchangeResponse.exchange:type_name -> securities.StockExchange
	15, // 5: securities.GetWorkingHoursResponse.hours:type_name -> securities.ExchangeWorkingHours
	15, // 6: securities.SetWorkingHoursResponse.hours:type_name -> securities.ExchangeWorkingHours
	20, // 7: securities.GetHolidaysResponse.holidays:type_name -> securities.ExchangeHoliday
	20, // 8: securities.AddHolidayResponse.holiday:type_name -> securities.ExchangeHoliday
	34, // 9: securities.GetListingsResponse.listings:type_name -> securities.ListingSummary
	34, // 10: securities.GetListingByIdResponse.summary:type_name -> securities.ListingSummary
	37, // 11: securities.GetListingByIdResponse.price_history:type_name -> securities.DailyPriceInfo
	38, // 12: securities.GetListingByIdResponse.stock:type_name -> securities.StockDetail
	39, // 13: securities.GetListingByIdResponse.forex:type_name -> securities.ForexDetail
	40, // 14: securities.GetListingByIdResponse.futures:type_name -> securities.FuturesDetail
	41, // 15: securities.GetListingByIdResponse.option:type_name -> securities.OptionDetail
	37, // 16: securities.GetListingHistoryResponse.history:type_name -> securities.DailyPriceInfo
	0,  // 17: securities.SecuritiesService.Ping:input_type -> securities.PingRequest
	3,  // 18: securities.SecuritiesService.GetStockExchanges:input_type -> securities.GetStockExchangesRequest
	5,  // 19: securities.SecuritiesService.GetStockExchangeByMIC:input_type -> securities.GetStockExchangeByMICRequest
	7,  // 20: securities.SecuritiesService.GetStockExchangeById:input_type -> securities.GetStockExchangeByIdRequest
	9,  // 21: securities.SecuritiesService.CreateStockExchange:input_type -> securities.CreateStockExchangeRequest
	11, // 22: securities.SecuritiesService.UpdateStockExchange:input_type -> securities.UpdateStockExchangeRequest
	13, // 23: securities.SecuritiesService.DeleteStockExchange:input_type -> securities.DeleteStockExchangeRequest
	16, // 24: securities.SecuritiesService.GetWorkingHours:input_type -> securities.GetWorkingHoursRequest
	18, // 25: securities.SecuritiesService.SetWorkingHours:input_type -> securities.SetWorkingHoursRequest
	21, // 26: securities.SecuritiesService.GetHolidays:input_type -> securities.GetHolidaysRequest
	23, // 27: securities.SecuritiesService.AddHoliday:input_type -> securities.AddHolidayRequest
	25, // 28: securities.SecuritiesService.DeleteHoliday:input_type -> securities.DeleteHolidayRequest
	27, // 29: securities.SecuritiesService.IsExchangeOpen:input_type -> securities.IsExchangeOpenRequest
	29, // 30: securities.SecuritiesService.GetTestMode:input_type -> securities.GetTestModeRequest
	31, // 31: securities.SecuritiesService.SetTestMode:input_type -> securities.SetTestModeRequest
	33, // 32: securities.SecuritiesService.GetListings:input_type -> securities.GetListingsRequest
	36, // 33: securities.SecuritiesService.GetListingById:input_type -> securities.GetListingByIdRequest
	43, // 34: securities.SecuritiesService.GetListingHistory:input_type -> securities.GetListingHistoryRequest
	1,  // 35: securities.SecuritiesService.Ping:output_type -> securities.PingResponse
	4,  // 36: securities.SecuritiesService.GetStockExchanges:output_type -> securities.GetStockExchangesResponse
	6,  // 37: securities.SecuritiesService.GetStockExchangeByMIC:output_type -> securities.GetStockExchangeByMICResponse
	8,  // 38: securities.SecuritiesService.GetStockExchangeById:output_type -> securities.GetStockExchangeByIdResponse
	10, // 39: securities.SecuritiesService.CreateStockExchange:output_type -> securities.CreateStockExchangeResponse
	12, // 40: securities.SecuritiesService.UpdateStockExchange:output_type -> securities.UpdateStockExchangeResponse
	14, // 41: securities.SecuritiesService.DeleteStockExchange:output_type -> securities.DeleteStockExchangeResponse
	17, // 42: securities.SecuritiesService.GetWorkingHours:output_type -> securities.GetWorkingHoursResponse
	19, // 43: securities.SecuritiesService.SetWorkingHours:output_type -> securities.SetWorkingHoursResponse
	22, // 44: securities.SecuritiesService.GetHolidays:output_type -> securities.GetHolidaysResponse
	24, // 45: securities.SecuritiesService.AddHoliday:output_type -> securities.AddHolidayResponse
	26, // 46: securities.SecuritiesService.DeleteHoliday:output_type -> securities.DeleteHolidayResponse
	28, // 47: securities.SecuritiesService.IsExchangeOpen:output_type -> securities.IsExchangeOpenResponse
	30, // 48: securities.SecuritiesService.GetTestMode:output_type -> securities.GetTestModeResponse
	32, // 49: securities.SecuritiesService.SetTestMode:output_type -> securities.SetTestModeResponse
	35, // 50: securities.SecuritiesService.GetListings:output_type -> securities.GetListingsResponse
	42, // 51: securities.SecuritiesService.GetListingById:output_type -> securities.GetListingByIdResponse
	44, // 52: securities.SecuritiesService.GetListingHistory:output_type -> securities.GetListingHistoryResponse
	35, // [35:53] is the sub-list for method output_type
	17, // [17:35] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_securities_proto_init() }
func file_securities_proto_init() {
	if File_securities_proto != nil {
		return
	}
	file_securities_proto_msgTypes[42].OneofWrappers = []any{
		(*GetListingByIdResponse_Stock)(nil),
		(*GetListingByIdResponse_Forex)(nil),
		(*GetListingByIdResponse_Futures)(nil),
		(*GetListingByIdResponse_Option)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_securities_proto_rawDesc), len(file_securities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   45,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_securities_proto_goTypes,
		DependencyIndexes: file_securities_proto_depIdxs,
		MessageInfos:      file_securities_proto_msgTypes,
	}.Build()
	File_securities_proto = out.File
	file_securities_proto_goTypes = nil
	file_securities_proto_depIdxs = nil
}
