// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: employee.proto

package employee

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Employee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender        string                 `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Username      string                 `protobuf:"bytes,9,opt,name=username,proto3" json:"username,omitempty"`
	Position      string                 `protobuf:"bytes,10,opt,name=position,proto3" json:"position,omitempty"`
	Department    string                 `protobuf:"bytes,11,opt,name=department,proto3" json:"department,omitempty"`
	Active        bool                   `protobuf:"varint,12,opt,name=active,proto3" json:"active,omitempty"`
	Permissions   []string               `protobuf:"bytes,13,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Jmbg          string                 `protobuf:"bytes,14,opt,name=jmbg,proto3" json:"jmbg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Employee) Reset() {
	*x = Employee{}
	mi := &file_employee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{0}
}

func (x *Employee) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Employee) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Employee) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Employee) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *Employee) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Employee) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Employee) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Employee) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Employee) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Employee) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Employee) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *Employee) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Employee) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Employee) GetJmbg() string {
	if x != nil {
		return x.Jmbg
	}
	return ""
}

type GetAllEmployeesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllEmployeesRequest) Reset() {
	*x = GetAllEmployeesRequest{}
	mi := &file_employee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllEmployeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllEmployeesRequest) ProtoMessage() {}

func (x *GetAllEmployeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllEmployeesRequest.ProtoReflect.Descriptor instead.
func (*GetAllEmployeesRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllEmployeesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllEmployeesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetAllEmployeesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employees     []*Employee            `protobuf:"bytes,1,rep,name=employees,proto3" json:"employees,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllEmployeesResponse) Reset() {
	*x = GetAllEmployeesResponse{}
	mi := &file_employee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllEmployeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllEmployeesResponse) ProtoMessage() {}

func (x *GetAllEmployeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllEmployeesResponse.ProtoReflect.Descriptor instead.
func (*GetAllEmployeesResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllEmployeesResponse) GetEmployees() []*Employee {
	if x != nil {
		return x.Employees
	}
	return nil
}

func (x *GetAllEmployeesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type SearchEmployeesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Position      string                 `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEmployeesRequest) Reset() {
	*x = SearchEmployeesRequest{}
	mi := &file_employee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEmployeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEmployeesRequest) ProtoMessage() {}

func (x *SearchEmployeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEmployeesRequest.ProtoReflect.Descriptor instead.
func (*SearchEmployeesRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{3}
}

func (x *SearchEmployeesRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SearchEmployeesRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *SearchEmployeesRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *SearchEmployeesRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *SearchEmployeesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchEmployeesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchEmployeesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employees     []*Employee            `protobuf:"bytes,1,rep,name=employees,proto3" json:"employees,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEmployeesResponse) Reset() {
	*x = SearchEmployeesResponse{}
	mi := &file_employee_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEmployeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEmployeesResponse) ProtoMessage() {}

func (x *SearchEmployeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEmployeesResponse.ProtoReflect.Descriptor instead.
func (*SearchEmployeesResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{4}
}

func (x *SearchEmployeesResponse) GetEmployees() []*Employee {
	if x != nil {
		return x.Employees
	}
	return nil
}

func (x *SearchEmployeesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetEmployeeCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeCredentialsRequest) Reset() {
	*x = GetEmployeeCredentialsRequest{}
	mi := &file_employee_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeCredentialsRequest) ProtoMessage() {}

func (x *GetEmployeeCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeCredentialsRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{5}
}

func (x *GetEmployeeCredentialsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetEmployeeCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Permissions   []string               `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeCredentialsResponse) Reset() {
	*x = GetEmployeeCredentialsResponse{}
	mi := &file_employee_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeCredentialsResponse) ProtoMessage() {}

func (x *GetEmployeeCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeCredentialsResponse.ProtoReflect.Descriptor instead.
func (*GetEmployeeCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{6}
}

func (x *GetEmployeeCredentialsResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetEmployeeCredentialsResponse) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *GetEmployeeCredentialsResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *GetEmployeeCredentialsResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type CreateEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,3,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender        string                 `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address       string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	Username      string                 `protobuf:"bytes,8,opt,name=username,proto3" json:"username,omitempty"`
	Position      string                 `protobuf:"bytes,9,opt,name=position,proto3" json:"position,omitempty"`
	Department    string                 `protobuf:"bytes,10,opt,name=department,proto3" json:"department,omitempty"`
	Jmbg          string                 `protobuf:"bytes,11,opt,name=jmbg,proto3" json:"jmbg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmployeeRequest) Reset() {
	*x = CreateEmployeeRequest{}
	mi := &file_employee_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmployeeRequest) ProtoMessage() {}

func (x *CreateEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmployeeRequest.ProtoReflect.Descriptor instead.
func (*CreateEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{7}
}

func (x *CreateEmployeeRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateEmployeeRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateEmployeeRequest) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *CreateEmployeeRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CreateEmployeeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateEmployeeRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateEmployeeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateEmployeeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateEmployeeRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *CreateEmployeeRequest) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *CreateEmployeeRequest) GetJmbg() string {
	if x != nil {
		return x.Jmbg
	}
	return ""
}

type CreateEmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *Employee              `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmployeeResponse) Reset() {
	*x = CreateEmployeeResponse{}
	mi := &file_employee_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmployeeResponse) ProtoMessage() {}

func (x *CreateEmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmployeeResponse.ProtoReflect.Descriptor instead.
func (*CreateEmployeeResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{8}
}

func (x *CreateEmployeeResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

type GetEmployeeByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeByIdRequest) Reset() {
	*x = GetEmployeeByIdRequest{}
	mi := &file_employee_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeByIdRequest) ProtoMessage() {}

func (x *GetEmployeeByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeByIdRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeByIdRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{9}
}

func (x *GetEmployeeByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEmployeeByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *Employee              `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeByIdResponse) Reset() {
	*x = GetEmployeeByIdResponse{}
	mi := &file_employee_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeByIdResponse) ProtoMessage() {}

func (x *GetEmployeeByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeByIdResponse.ProtoReflect.Descriptor instead.
func (*GetEmployeeByIdResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{10}
}

func (x *GetEmployeeByIdResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

type UpdateEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender        string                 `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Username      string                 `protobuf:"bytes,9,opt,name=username,proto3" json:"username,omitempty"`
	Position      string                 `protobuf:"bytes,10,opt,name=position,proto3" json:"position,omitempty"`
	Department    string                 `protobuf:"bytes,11,opt,name=department,proto3" json:"department,omitempty"`
	Active        bool                   `protobuf:"varint,12,opt,name=active,proto3" json:"active,omitempty"`
	Permissions   []string               `protobuf:"bytes,13,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Jmbg          string                 `protobuf:"bytes,14,opt,name=jmbg,proto3" json:"jmbg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmployeeRequest) Reset() {
	*x = UpdateEmployeeRequest{}
	mi := &file_employee_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmployeeRequest) ProtoMessage() {}

func (x *UpdateEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmployeeRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateEmployeeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateEmployeeRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *UpdateEmployeeRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *UpdateEmployeeRequest) GetJmbg() string {
	if x != nil {
		return x.Jmbg
	}
	return ""
}

type UpdateEmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *Employee              `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmployeeResponse) Reset() {
	*x = UpdateEmployeeResponse{}
	mi := &file_employee_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmployeeResponse) ProtoMessage() {}

func (x *UpdateEmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmployeeResponse.ProtoReflect.Descriptor instead.
func (*UpdateEmployeeResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateEmployeeResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

type ActivateEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateEmployeeRequest) Reset() {
	*x = ActivateEmployeeRequest{}
	mi := &file_employee_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateEmployeeRequest) ProtoMessage() {}

func (x *ActivateEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateEmployeeRequest.ProtoReflect.Descriptor instead.
func (*ActivateEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{13}
}

func (x *ActivateEmployeeRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *ActivateEmployeeRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type ActivateEmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateEmployeeResponse) Reset() {
	*x = ActivateEmployeeResponse{}
	mi := &file_employee_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateEmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateEmployeeResponse) ProtoMessage() {}

func (x *ActivateEmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateEmployeeResponse.ProtoReflect.Descriptor instead.
func (*ActivateEmployeeResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{14}
}

type GetEmployeeByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeByEmailRequest) Reset() {
	*x = GetEmployeeByEmailRequest{}
	mi := &file_employee_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeByEmailRequest) ProtoMessage() {}

func (x *GetEmployeeByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeByEmailRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{15}
}

func (x *GetEmployeeByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetEmployeeByEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeByEmailResponse) Reset() {
	*x = GetEmployeeByEmailResponse{}
	mi := &file_employee_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeByEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeByEmailResponse) ProtoMessage() {}

func (x *GetEmployeeByEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeByEmailResponse.ProtoReflect.Descriptor instead.
func (*GetEmployeeByEmailResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{16}
}

func (x *GetEmployeeByEmailResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetEmployeeByEmailResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GetEmployeeByEmailResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UpdatePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordRequest) Reset() {
	*x = UpdatePasswordRequest{}
	mi := &file_employee_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRequest) ProtoMessage() {}

func (x *UpdatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{17}
}

func (x *UpdatePasswordRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *UpdatePasswordRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type UpdatePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordResponse) Reset() {
	*x = UpdatePasswordResponse{}
	mi := &file_employee_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordResponse) ProtoMessage() {}

func (x *UpdatePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordResponse.ProtoReflect.Descriptor instead.
func (*UpdatePasswordResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{18}
}

type ActuaryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Position      string                 `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	LimitAmount   float64                `protobuf:"fixed64,6,opt,name=limit_amount,json=limitAmount,proto3" json:"limit_amount,omitempty"`
	UsedLimit     float64                `protobuf:"fixed64,7,opt,name=used_limit,json=usedLimit,proto3" json:"used_limit,omitempty"`
	NeedApproval  bool                   `protobuf:"varint,8,opt,name=need_approval,json=needApproval,proto3" json:"need_approval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActuaryInfo) Reset() {
	*x = ActuaryInfo{}
	mi := &file_employee_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActuaryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActuaryInfo) ProtoMessage() {}

func (x *ActuaryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActuaryInfo.ProtoReflect.Descriptor instead.
func (*ActuaryInfo) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{19}
}

func (x *ActuaryInfo) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *ActuaryInfo) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ActuaryInfo) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ActuaryInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ActuaryInfo) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *ActuaryInfo) GetLimitAmount() float64 {
	if x != nil {
		return x.LimitAmount
	}
	return 0
}

func (x *ActuaryInfo) GetUsedLimit() float64 {
	if x != nil {
		return x.UsedLimit
	}
	return 0
}

func (x *ActuaryInfo) GetNeedApproval() bool {
	if x != nil {
		return x.NeedApproval
	}
	return false
}

type GetActuariesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Position      string                 `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActuariesRequest) Reset() {
	*x = GetActuariesRequest{}
	mi := &file_employee_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActuariesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActuariesRequest) ProtoMessage() {}

func (x *GetActuariesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActuariesRequest.ProtoReflect.Descriptor instead.
func (*GetActuariesRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{20}
}

func (x *GetActuariesRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetActuariesRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GetActuariesRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *GetActuariesRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

type GetActuariesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actuaries     []*ActuaryInfo         `protobuf:"bytes,1,rep,name=actuaries,proto3" json:"actuaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActuariesResponse) Reset() {
	*x = GetActuariesResponse{}
	mi := &file_employee_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActuariesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActuariesResponse) ProtoMessage() {}

func (x *GetActuariesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActuariesResponse.ProtoReflect.Descriptor instead.
func (*GetActuariesResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{21}
}

func (x *GetActuariesResponse) GetActuaries() []*ActuaryInfo {
	if x != nil {
		return x.Actuaries
	}
	return nil
}

type SetAgentLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	LimitAmount   float64                `protobuf:"fixed64,2,opt,name=limit_amount,json=limitAmount,proto3" json:"limit_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAgentLimitRequest) Reset() {
	*x = SetAgentLimitRequest{}
	mi := &file_employee_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAgentLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAgentLimitRequest) ProtoMessage() {}

func (x *SetAgentLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAgentLimitRequest.ProtoReflect.Descriptor instead.
func (*SetAgentLimitRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{22}
}

func (x *SetAgentLimitRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *SetAgentLimitRequest) GetLimitAmount() float64 {
	if x != nil {
		return x.LimitAmount
	}
	return 0
}

type SetAgentLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAgentLimitResponse) Reset() {
	*x = SetAgentLimitResponse{}
	mi := &file_employee_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAgentLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAgentLimitResponse) ProtoMessage() {}

func (x *SetAgentLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAgentLimitResponse.ProtoReflect.Descriptor instead.
func (*SetAgentLimitResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{23}
}

type ResetAgentUsedLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetAgentUsedLimitRequest) Reset() {
	*x = ResetAgentUsedLimitRequest{}
	mi := &file_employee_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetAgentUsedLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetAgentUsedLimitRequest) ProtoMessage() {}

func (x *ResetAgentUsedLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetAgentUsedLimitRequest.ProtoReflect.Descriptor instead.
func (*ResetAgentUsedLimitRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{24}
}

func (x *ResetAgentUsedLimitRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

type ResetAgentUsedLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetAgentUsedLimitResponse) Reset() {
	*x = ResetAgentUsedLimitResponse{}
	mi := &file_employee_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetAgentUsedLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetAgentUsedLimitResponse) ProtoMessage() {}

func (x *ResetAgentUsedLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetAgentUsedLimitResponse.ProtoReflect.Descriptor instead.
func (*ResetAgentUsedLimitResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{25}
}

type SetNeedApprovalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    int64                  `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	NeedApproval  bool                   `protobuf:"varint,2,opt,name=need_approval,json=needApproval,proto3" json:"need_approval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNeedApprovalRequest) Reset() {
	*x = SetNeedApprovalRequest{}
	mi := &file_employee_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNeedApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNeedApprovalRequest) ProtoMessage() {}

func (x *SetNeedApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNeedApprovalRequest.ProtoReflect.Descriptor instead.
func (*SetNeedApprovalRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{26}
}

func (x *SetNeedApprovalRequest) GetEmployeeId() int64 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *SetNeedApprovalRequest) GetNeedApproval() bool {
	if x != nil {
		return x.NeedApproval
	}
	return false
}

type SetNeedApprovalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNeedApprovalResponse) Reset() {
	*x = SetNeedApprovalResponse{}
	mi := &file_employee_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNeedApprovalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNeedApprovalResponse) ProtoMessage() {}

func (x *SetNeedApprovalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNeedApprovalResponse.ProtoReflect.Descriptor instead.
func (*SetNeedApprovalResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{27}
}

type ResetAllActuaryUsedLimitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetAllActuaryUsedLimitsRequest) Reset() {
	*x = ResetAllActuaryUsedLimitsRequest{}
	mi := &file_employee_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetAllActuaryUsedLimitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetAllActuaryUsedLimitsRequest) ProtoMessage() {}

func (x *ResetAllActuaryUsedLimitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetAllActuaryUsedLimitsRequest.ProtoReflect.Descriptor instead.
func (*ResetAllActuaryUsedLimitsRequest) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{28}
}

type ResetAllActuaryUsedLimitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetAllActuaryUsedLimitsResponse) Reset() {
	*x = ResetAllActuaryUsedLimitsResponse{}
	mi := &file_employee_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetAllActuaryUsedLimitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetAllActuaryUsedLimitsResponse) ProtoMessage() {}

func (x *ResetAllActuaryUsedLimitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_employee_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetAllActuaryUsedLimitsResponse.ProtoReflect.Descriptor instead.
func (*ResetAllActuaryUsedLimitsResponse) Descriptor() ([]byte, []int) {
	return file_employee_proto_rawDescGZIP(), []int{29}
}

var File_employee_proto protoreflect.FileDescriptor

const file_employee_proto_rawDesc = "" +
	"\n" +
	"\x0eemployee.proto\x12\bemployee\"\x8b\x03\n" +
	"\bEmployee\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\"\n" +
	"\rdate_of_birth\x18\x04 \x01(\tR\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\a \x01(\tR\vphoneNumber\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x1a\n" +
	"\busername\x18\t \x01(\tR\busername\x12\x1a\n" +
	"\bposition\x18\n" +
	" \x01(\tR\bposition\x12\x1e\n" +
	"\n" +
	"department\x18\v \x01(\tR\n" +
	"department\x12\x16\n" +
	"\x06active\x18\f \x01(\bR\x06active\x12 \n" +
	"\vpermissions\x18\r \x03(\tR\vpermissions\x12\x12\n" +
	"\x04jmbg\x18\x0e \x01(\tR\x04jmbg\"I\n" +
	"\x16GetAllEmployeesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"l\n" +
	"\x17GetAllEmployeesResponse\x120\n" +
	"\temployees\x18\x01 \x03(\v2\x12.employee.EmployeeR\temployees\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xb7\x01\n" +
	"\x16SearchEmployeesRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\tR\bposition\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"l\n" +
	"\x17SearchEmployeesResponse\x120\n" +
	"\temployees\x18\x01 \x03(\v2\x12.employee.EmployeeR\temployees\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"5\n" +
	"\x1dGetEmployeeCredentialsRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\x8f\x01\n" +
	"\x1eGetEmployeeCredentialsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\x12 \n" +
	"\vpermissions\x18\x03 \x03(\tR\vpermissions\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\"\xce\x02\n" +
	"\x15CreateEmployeeRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\"\n" +
	"\rdate_of_birth\x18\x03 \x01(\tR\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x06 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x12\x1a\n" +
	"\busername\x18\b \x01(\tR\busername\x12\x1a\n" +
	"\bposition\x18\t \x01(\tR\bposition\x12\x1e\n" +
	"\n" +
	"department\x18\n" +
	" \x01(\tR\n" +
	"department\x12\x12\n" +
	"\x04jmbg\x18\v \x01(\tR\x04jmbg\"H\n" +
	"\x16CreateEmployeeResponse\x12.\n" +
	"\bemployee\x18\x01 \x01(\v2\x12.employee.EmployeeR\bemployee\"(\n" +
	"\x16GetEmployeeByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"I\n" +
	"\x17GetEmployeeByIdResponse\x12.\n" +
	"\bemployee\x18\x01 \x01(\v2\x12.employee.EmployeeR\bemployee\"\x98\x03\n" +
	"\x15UpdateEmployeeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\"\n" +
	"\rdate_of_birth\x18\x04 \x01(\tR\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\a \x01(\tR\vphoneNumber\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x1a\n" +
	"\busername\x18\t \x01(\tR\busername\x12\x1a\n" +
	"\bposition\x18\n" +
	" \x01(\tR\bposition\x12\x1e\n" +
	"\n" +
	"department\x18\v \x01(\tR\n" +
	"department\x12\x16\n" +
	"\x06active\x18\f \x01(\bR\x06active\x12 \n" +
	"\vpermissions\x18\r \x03(\tR\vpermissions\x12\x12\n" +
	"\x04jmbg\x18\x0e \x01(\tR\x04jmbg\"H\n" +
	"\x16UpdateEmployeeResponse\x12.\n" +
	"\bemployee\x18\x01 \x01(\v2\x12.employee.EmployeeR\bemployee\"_\n" +
	"\x17ActivateEmployeeRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x03R\n" +
	"employeeId\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\"\x1a\n" +
	"\x18ActivateEmployeeResponse\"1\n" +
	"\x19GetEmployeeByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"a\n" +
	"\x1aGetEmployeeByEmailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"]\n" +
	"\x15UpdatePasswordRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x03R\n" +
	"employeeId\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\"\x18\n" +
	"\x16UpdatePasswordResponse\"\x83\x02\n" +
	"\vActuaryInfo\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x03R\n" +
	"employeeId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\tR\bposition\x12!\n" +
	"\flimit_amount\x18\x06 \x01(\x01R\vlimitAmount\x12\x1d\n" +
	"\n" +
	"used_limit\x18\a \x01(\x01R\tusedLimit\x12#\n" +
	"\rneed_approval\x18\b \x01(\bR\fneedApproval\"\x83\x01\n" +
	"\x13GetActuariesRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\tR\bposition\"K\n" +
	"\x14GetActuariesResponse\x123\n" +
	"\tactuaries\x18\x01 \x03(\v2\x15.employee.ActuaryInfoR\tactuaries\"Z\n" +
	"\x14SetAgentLimitRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x03R\n" +
	"employeeId\x12!\n" +
	"\flimit_amount\x18\x02 \x01(\x01R\vlimitAmount\"\x17\n" +
	"\x15SetAgentLimitResponse\"=\n" +
	"\x1aResetAgentUsedLimitRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x03R\n" +
	"employeeId\"\x1d\n" +
	"\x1bResetAgentUsedLimitResponse\"^\n" +
	"\x16SetNeedApprovalRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\x03R\n" +
	"employeeId\x12#\n" +
	"\rneed_approval\x18\x02 \x01(\bR\fneedApproval\"\x19\n" +
	"\x17SetNeedApprovalResponse\"\"\n" +
	" ResetAllActuaryUsedLimitsRequest\"#\n" +
	"!ResetAllActuaryUsedLimitsResponse2\x94\n" +
	"\n" +
	"\x0fEmployeeService\x12V\n" +
	"\x0fGetAllEmployees\x12 .employee.GetAllEmployeesRequest\x1a!.employee.GetAllEmployeesResponse\x12V\n" +
	"\x0fSearchEmployees\x12 .employee.SearchEmployeesRequest\x1a!.employee.SearchEmployeesResponse\x12k\n" +
	"\x16GetEmployeeCredentials\x12'.employee.GetEmployeeCredentialsRequest\x1a(.employee.GetEmployeeCredentialsResponse\x12S\n" +
	"\x0eCreateEmployee\x12\x1f.employee.CreateEmployeeRequest\x1a .employee.CreateEmployeeResponse\x12V\n" +
	"\x0fGetEmployeeById\x12 .employee.GetEmployeeByIdRequest\x1a!.employee.GetEmployeeByIdResponse\x12S\n" +
	"\x0eUpdateEmployee\x12\x1f.employee.UpdateEmployeeRequest\x1a .employee.UpdateEmployeeResponse\x12Y\n" +
	"\x10ActivateEmployee\x12!.employee.ActivateEmployeeRequest\x1a\".employee.ActivateEmployeeResponse\x12_\n" +
	"\x12GetEmployeeByEmail\x12#.employee.GetEmployeeByEmailRequest\x1a$.employee.GetEmployeeByEmailResponse\x12S\n" +
	"\x0eUpdatePassword\x12\x1f.employee.UpdatePasswordRequest\x1a .employee.UpdatePasswordResponse\x12M\n" +
	"\fGetActuaries\x12\x1d.employee.GetActuariesRequest\x1a\x1e.employee.GetActuariesResponse\x12P\n" +
	"\rSetAgentLimit\x12\x1e.employee.SetAgentLimitRequest\x1a\x1f.employee.SetAgentLimitResponse\x12b\n" +
	"\x13ResetAgentUsedLimit\x12$.employee.ResetAgentUsedLimitRequest\x1a%.employee.ResetAgentUsedLimitResponse\x12V\n" +
	"\x0fSetNeedApproval\x12 .employee.SetNeedApprovalRequest\x1a!.employee.SetNeedApprovalResponse\x12t\n" +
	"\x19ResetAllActuaryUsedLimits\x12*.employee.ResetAllActuaryUsedLimitsRequest\x1a+.employee.ResetAllActuaryUsedLimitsResponseB=Z;github.com/RAF-SI-2025/EXBanka-4-Backend/shared/pb/employeeb\x06proto3"

var (
	file_employee_proto_rawDescOnce sync.Once
	file_employee_proto_rawDescData []byte
)

func file_employee_proto_rawDescGZIP() []byte {
	file_employee_proto_rawDescOnce.Do(func() {
		file_employee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_employee_proto_rawDesc), len(file_employee_proto_rawDesc)))
	})
	return file_employee_proto_rawDescData
}

var file_employee_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_employee_proto_goTypes = []any{
	(*Employee)(nil),                          // 0: employee.Employee
	(*GetAllEmployeesRequest)(nil),            // 1: employee.GetAllEmployeesRequest
	(*GetAllEmployeesResponse)(nil),           // 2: employee.GetAllEmployeesResponse
	(*SearchEmployeesRequest)(nil),            // 3: employee.SearchEmployeesRequest
	(*SearchEmployeesResponse)(nil),           // 4: employee.SearchEmployeesResponse
	(*GetEmployeeCredentialsRequest)(nil),     // 5: employee.GetEmployeeCredentialsRequest
	(*GetEmployeeCredentialsResponse)(nil),    // 6: employee.GetEmployeeCredentialsResponse
	(*CreateEmployeeRequest)(nil),             // 7: employee.CreateEmployeeRequest
	(*CreateEmployeeResponse)(nil),            // 8: employee.CreateEmployeeResponse
	(*GetEmployeeByIdRequest)(nil),            // 9: employee.GetEmployeeByIdRequest
	(*GetEmployeeByIdResponse)(nil),           // 10: employee.GetEmployeeByIdResponse
	(*UpdateEmployeeRequest)(nil),             // 11: employee.UpdateEmployeeRequest
	(*UpdateEmployeeResponse)(nil),            // 12: employee.UpdateEmployeeResponse
	(*ActivateEmployeeRequest)(nil),           // 13: employee.ActivateEmployeeRequest
	(*ActivateEmployeeResponse)(nil),          // 14: employee.ActivateEmployeeResponse
	(*GetEmployeeByEmailRequest)(nil),         // 15: employee.GetEmployeeByEmailRequest
	(*GetEmployeeByEmailResponse)(nil),        // 16: employee.GetEmployeeByEmailResponse
	(*UpdatePasswordRequest)(nil),             // 17: employee.UpdatePasswordRequest
	(*UpdatePasswordResponse)(nil),            // 18: employee.UpdatePasswordResponse
	(*ActuaryInfo)(nil),                       // 19: employee.ActuaryInfo
	(*GetActuariesRequest)(nil),               // 20: employee.GetActuariesRequest
	(*GetActuariesResponse)(nil),              // 21: employee.GetActuariesResponse
	(*SetAgentLimitRequest)(nil),              // 22: employee.SetAgentLimitRequest
	(*SetAgentLimitResponse)(nil),             // 23: employee.SetAgentLimitResponse
	(*ResetAgentUsedLimitRequest)(nil),        // 24: employee.ResetAgentUsedLimitRequest
	(*ResetAgentUsedLimitResponse)(nil),       // 25: employee.ResetAgentUsedLimitResponse
	(*SetNeedApprovalRequest)(nil),            // 26: employee.SetNeedApprovalRequest
	(*SetNeedApprovalResponse)(nil),           // 27: employee.SetNeedApprovalResponse
	(*ResetAllActuaryUsedLimitsRequest)(nil),  // 28: employee.ResetAllActuaryUsedLimitsRequest
	(*ResetAllActuaryUsedLimitsResponse)(nil), // 29: employee.ResetAllActuaryUsedLimitsResponse
}
var file_employee_proto_depIdxs = []int32{
	0,  // 0: employee.GetAllEmployeesResponse.employees:type_name -> employee.Employee
	0,  // 1: employee.SearchEmployeesResponse.employees:type_name -> employee.Employee
	0,  // 2: employee.CreateEmployeeResponse.employee:type_name -> employee.Employee
	0,  // 3: employee.GetEmployeeByIdResponse.employee:type_name -> employee.Employee
	0,  // 4: employee.UpdateEmployeeResponse.employee:type_name -> employee.Employee
	19, // 5: employee.GetActuariesResponse.actuaries:type_name -> employee.ActuaryInfo
	1,  // 6: employee.EmployeeService.GetAllEmployees:input_type -> employee.GetAllEmployeesRequest
	3,  // 7: employee.EmployeeService.SearchEmployees:input_type -> employee.SearchEmployeesRequest
	5,  // 8: employee.EmployeeService.GetEmployeeCredentials:input_type -> employee.GetEmployeeCredentialsRequest
	7,  // 9: employee.EmployeeService.CreateEmployee:input_type -> employee.CreateEmployeeRequest
	9,  // 10: employee.EmployeeService.GetEmployeeById:input_type -> employee.GetEmployeeByIdRequest
	11, // 11: employee.EmployeeService.UpdateEmployee:input_type -> employee.UpdateEmployeeRequest
	13, // 12: employee.EmployeeService.ActivateEmployee:input_type -> employee.ActivateEmployeeRequest
	15, // 13: employee.EmployeeService.GetEmployeeByEmail:input_type -> employee.GetEmployeeByEmailRequest
	17, // 14: employee.EmployeeService.UpdatePassword:input_type -> employee.UpdatePasswordRequest
	20, // 15: employee.EmployeeService.GetActuaries:input_type -> employee.GetActuariesRequest
	22, // 16: employee.EmployeeService.SetAgentLimit:input_type -> employee.SetAgentLimitRequest
	24, // 17: employee.EmployeeService.ResetAgentUsedLimit:input_type -> employee.ResetAgentUsedLimitRequest
	26, // 18: employee.EmployeeService.SetNeedApproval:input_type -> employee.SetNeedApprovalRequest
	28, // 19: employee.EmployeeService.ResetAllActuaryUsedLimits:input_type -> employee.ResetAllActuaryUsedLimitsRequest
	2,  // 20: employee.EmployeeService.GetAllEmployees:output_type -> employee.GetAllEmployeesResponse
	4,  // 21: employee.EmployeeService.SearchEmployees:output_type -> employee.SearchEmployeesResponse
	6,  // 22: employee.EmployeeService.GetEmployeeCredentials:output_type -> employee.GetEmployeeCredentialsResponse
	8,  // 23: employee.EmployeeService.CreateEmployee:output_type -> employee.CreateEmployeeResponse
	10, // 24: employee.EmployeeService.GetEmployeeById:output_type -> employee.GetEmployeeByIdResponse
	12, // 25: employee.EmployeeService.UpdateEmployee:output_type -> employee.UpdateEmployeeResponse
	14, // 26: employee.EmployeeService.ActivateEmployee:output_type -> employee.ActivateEmployeeResponse
	16, // 27: employee.EmployeeService.GetEmployeeByEmail:output_type -> employee.GetEmployeeByEmailResponse
	18, // 28: employee.EmployeeService.UpdatePassword:output_type -> employee.UpdatePasswordResponse
	21, // 29: employee.EmployeeService.GetActuaries:output_type -> employee.GetActuariesResponse
	23, // 30: employee.EmployeeService.SetAgentLimit:output_type -> employee.SetAgentLimitResponse
	25, // 31: employee.EmployeeService.ResetAgentUsedLimit:output_type -> employee.ResetAgentUsedLimitResponse
	27, // 32: employee.EmployeeService.SetNeedApproval:output_type -> employee.SetNeedApprovalResponse
	29, // 33: employee.EmployeeService.ResetAllActuaryUsedLimits:output_type -> employee.ResetAllActuaryUsedLimitsResponse
	20, // [20:34] is the sub-list for method output_type
	6,  // [6:20] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_employee_proto_init() }
func file_employee_proto_init() {
	if File_employee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_employee_proto_rawDesc), len(file_employee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_employee_proto_goTypes,
		DependencyIndexes: file_employee_proto_depIdxs,
		MessageInfos:      file_employee_proto_msgTypes,
	}.Build()
	File_employee_proto = out.File
	file_employee_proto_goTypes = nil
	file_employee_proto_depIdxs = nil
}
